import { apiFetch } from './client';

export type Goal = { id: string; name: string; description: string | null; targetAmount: string; currentAmount: string; remainingAmount: string; progress: number; status: 'ACTIVE' | 'NEAR_TARGET' | 'COMPLETED' | 'OVERDUE'; currency: 'USD' | 'SOS'; startDate: string; targetDate: string; isActive: boolean; createdAt: string; updatedAt: string; recentEntries?: GoalEntry[] };
export type GoalEntry = { id: string; type: 'CONTRIBUTION' | 'WITHDRAWAL'; amount: string; description: string | null; date: string; createdAt: string };
export type GoalInput = { name: string; description?: string; targetAmount: string; currency: 'USD' | 'SOS'; startDate: string; targetDate: string };
export type GoalEntryInput = { amount: string; description?: string; date: string };
export type GoalQuery = { page?: number; limit?: number; search?: string; currency?: 'USD' | 'SOS'; status?: Goal['status']; isActive?: boolean };
export type GoalSummary = Record<'USD' | 'SOS', { targetAmount: string; savedAmount: string; remainingAmount: string; totalGoals: number; activeGoals: number; completedGoals: number; overdueGoals: number }>;
function queryString(query: Record<string, unknown>) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== '') params.set(key, String(value)); }); return params.toString(); }
export const goalsApi = { list: (query: GoalQuery) => apiFetch<{ data: Goal[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(`/goals?${queryString(query)}`), summary: () => apiFetch<GoalSummary>('/goals/summary'), get: (id: string) => apiFetch<Goal>(`/goals/${id}`), history: (id: string, page = 1) => apiFetch<{ data: GoalEntry[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(`/goals/${id}/history?page=${page}&limit=20`), create: (input: GoalInput) => apiFetch<Goal>('/goals', { method: 'POST', body: JSON.stringify(input) }), update: (id: string, input: GoalInput) => apiFetch<Goal>(`/goals/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), deactivate: (id: string) => apiFetch<unknown>(`/goals/${id}`, { method: 'DELETE' }), restore: (id: string) => apiFetch<Goal>(`/goals/${id}/restore`, { method: 'PATCH' }), contribute: (id: string, input: GoalEntryInput) => apiFetch<Goal>(`/goals/${id}/contribute`, { method: 'POST', body: JSON.stringify(input) }), withdraw: (id: string, input: GoalEntryInput) => apiFetch<Goal>(`/goals/${id}/withdraw`, { method: 'POST', body: JSON.stringify(input) }) };
