import { apiFetch } from './client';

export type RecurringFrequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';
export type RecurringTransaction = { id: string; type: 'INCOME' | 'EXPENSE'; categoryId: string; name: string; description: string | null; amount: string; currency: 'USD' | 'SOS'; frequency: RecurringFrequency; interval: number; startDate: string; endDate: string | null; nextRunDate: string; lastRunDate: string | null; isActive: boolean; isPaused: boolean; category: { id: string; name: string; type: 'INCOME' | 'EXPENSE'; icon: string | null }; _count?: { transactions: number } };
export type RecurringInput = { name: string; description?: string; type: 'INCOME' | 'EXPENSE'; categoryId: string; amount: string; currency: 'USD' | 'SOS'; frequency: RecurringFrequency; interval: number; startDate: string; endDate?: string | null };
export type RecurringQuery = { page?: number; limit?: number; type?: 'INCOME' | 'EXPENSE'; currency?: 'USD' | 'SOS'; isActive?: boolean; isPaused?: boolean; search?: string };
export type UpcomingOccurrence = { recurringTransactionId: string; name: string; type: 'INCOME' | 'EXPENSE'; amount: string; currency: 'USD' | 'SOS'; category: { id: string; name: string; type: 'INCOME' | 'EXPENSE'; icon: string | null }; occurrenceDate: string };
function queryString(query: Record<string, unknown>) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== '') params.set(key, String(value)); }); return params.toString(); }
export const recurringTransactionApi = { list: (query: RecurringQuery = {}) => apiFetch<{ data: RecurringTransaction[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(`/recurring-transactions?${queryString(query)}`), get: (id: string) => apiFetch<RecurringTransaction>(`/recurring-transactions/${id}`), upcoming: (days = 90) => apiFetch<UpcomingOccurrence[]>(`/recurring-transactions/upcoming?${queryString({ days })}`), create: (input: RecurringInput) => apiFetch<RecurringTransaction>('/recurring-transactions', { method: 'POST', body: JSON.stringify(input) }), update: (id: string, input: Partial<RecurringInput>) => apiFetch<RecurringTransaction>(`/recurring-transactions/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), pause: (id: string) => apiFetch<unknown>(`/recurring-transactions/${id}/pause`, { method: 'PATCH' }), resume: (id: string) => apiFetch<unknown>(`/recurring-transactions/${id}/resume`, { method: 'PATCH' }), restore: (id: string) => apiFetch<RecurringTransaction>(`/recurring-transactions/${id}/restore`, { method: 'PATCH' }), deactivate: (id: string) => apiFetch<unknown>(`/recurring-transactions/${id}`, { method: 'DELETE' }), process: (asOf?: string) => apiFetch<{ generated: number; occurrencesSkipped: number; schedulesProcessed: number }>(`/recurring-transactions/process${asOf ? `?asOf=${asOf}` : ''}`, { method: 'POST' }) };
