import { apiFetch } from './client';

export type Savings = { id: string; name: string; description: string | null; targetAmount: string; currentAmount: string; remainingAmount: string; progress: number; status: 'ACTIVE' | 'NEAR_TARGET' | 'COMPLETED' | 'OVERDUE'; currency: 'USD' | 'SOS'; startDate: string; targetDate: string; isActive: boolean; createdAt: string; updatedAt: string; recentEntries?: SavingsEntry[] };
export type SavingsEntry = { id: string; type: 'DEPOSIT' | 'WITHDRAWAL'; amount: string; description: string | null; date: string; createdAt: string };
export type SavingsInput = { name: string; description?: string; targetAmount: string; currency: 'USD' | 'SOS'; startDate: string; targetDate: string };
export type EntryInput = { amount: string; description?: string; date: string };
export type SavingsQuery = { page?: number; limit?: number; search?: string; currency?: 'USD' | 'SOS'; status?: Savings['status']; isActive?: boolean };
export type SavingsSummary = Record<'USD' | 'SOS', { targetAmount: string; savedAmount: string; remainingAmount: string; totalPlans: number; activePlans: number; completedPlans: number; overduePlans: number }>;
function queryString(query: Record<string, unknown>) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value !== undefined && value !== '') params.set(key, String(value)); }); return params.toString(); }
export const savingsApi = { list: (query: SavingsQuery) => apiFetch<{ data: Savings[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(`/savings?${queryString(query)}`), summary: () => apiFetch<SavingsSummary>('/savings/summary'), get: (id: string) => apiFetch<Savings>(`/savings/${id}`), history: (id: string, page = 1) => apiFetch<{ data: SavingsEntry[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(`/savings/${id}/history?page=${page}&limit=20`), create: (input: SavingsInput) => apiFetch<Savings>('/savings', { method: 'POST', body: JSON.stringify(input) }), update: (id: string, input: SavingsInput) => apiFetch<Savings>(`/savings/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), deactivate: (id: string) => apiFetch<unknown>(`/savings/${id}`, { method: 'DELETE' }), restore: (id: string) => apiFetch<Savings>(`/savings/${id}/restore`, { method: 'PATCH' }), deposit: (id: string, input: EntryInput) => apiFetch<Savings>(`/savings/${id}/deposit`, { method: 'POST', body: JSON.stringify(input) }), withdraw: (id: string, input: EntryInput) => apiFetch<Savings>(`/savings/${id}/withdraw`, { method: 'POST', body: JSON.stringify(input) }) };
