import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { z } from 'zod';
import { categoryApi, type Category } from '../../src/api/category.api';
import { colors } from '../../src/constants/theme';

const schema = z.object({ name: z.string().trim().min(1, 'Fadlan geli magaca category-ga.'), type: z.enum(['INCOME', 'EXPENSE']), icon: z.string().trim().regex(/^[a-z0-9-]*$/, 'Icon-ku waa inuu noqdaa identifier ammaan ah.').optional() });
type FormValues = z.infer<typeof schema>;
const iconMap: Record<string, string> = { utensils: '🍴', car: '▣', home: '⌂', briefcase: '▤', shopping: '▣', health: '+', gift: '◇', store: '▥', laptop: '▱', receipt: '▤', book: '▤', users: '◉', entertainment: '♪', dumbbell: '▣', shield: '◇' };

export default function CategoriesScreen() {
  const queryClient = useQueryClient(); const [type, setType] = useState<'INCOME' | 'EXPENSE' | undefined>(); const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [modal, setModal] = useState<{ mode: 'create' | 'edit'; category?: Category } | null>(null);
  useEffect(() => { const timer = setTimeout(() => setDebounced(search), 350); return () => clearTimeout(timer); }, [search]);
  const categoriesQuery = useQuery({ queryKey: ['categories', type, debounced], queryFn: () => categoryApi.list({ type, search: debounced || undefined, includeInactive: true }) });
  const statusMutation = useMutation({ mutationFn: ({ category, active }: { category: Category; active: boolean }) => active ? categoryApi.restore(category.id) : categoryApi.deactivate(category.id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['categories'] }) });
  const categories = categoriesQuery.data ?? [];
  function toggle(category: Category) { if (category.isDefault) return; Alert.alert(category.isActive ? 'Deactivate category' : 'Restore category', category.isActive ? 'Ma hubtaa inaad deactivate-gareyso category-gan?' : 'Ma rabtaa inaad restore-gareyso category-gan?', [{ text: 'Cancel', style: 'cancel' }, { text: category.isActive ? 'Deactivate' : 'Restore', style: category.isActive ? 'destructive' : 'default', onPress: () => statusMutation.mutate({ category, active: !category.isActive }) }]); }
  return <ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>QORSHE</Text><Text style={styles.title}>Categories</Text></View><Pressable style={styles.addButton} onPress={() => setModal({ mode: 'create' })}><Text style={styles.addText}>＋</Text></Pressable></View><TextInput style={styles.search} placeholder="Search categories…" value={search} onChangeText={setSearch} /><View style={styles.filters}><Filter label="All" active={!type} onPress={() => setType(undefined)} /><Filter label="Income" active={type === 'INCOME'} onPress={() => setType('INCOME')} /><Filter label="Expense" active={type === 'EXPENSE'} onPress={() => setType('EXPENSE')} /></View>{categoriesQuery.isLoading ? <Text style={styles.empty}>Loading categories…</Text> : categoriesQuery.isError ? <Text style={styles.error}>Category-yada lama soo gelin. Fadlan mar kale isku day.</Text> : categories.length === 0 ? <Text style={styles.empty}>{search ? 'Category-gaas lama helin.' : 'No categories found.'}</Text> : categories.map((category) => <CategoryCard key={category.id} category={category} onEdit={() => setModal({ mode: 'edit', category })} onToggle={() => toggle(category)} />)}{modal && <CategoryModal mode={modal.mode} category={modal.category} onClose={() => setModal(null)} onSaved={() => { setModal(null); queryClient.invalidateQueries({ queryKey: ['categories'] }); }} />}</ScrollView>;
}

function CategoryCard({ category, onEdit, onToggle }: { category: Category; onEdit: () => void; onToggle: () => void }) { return <View style={[styles.card, !category.isActive && styles.inactive]}><View style={[styles.icon, category.type === 'INCOME' ? styles.income : styles.expense]}><Text style={styles.iconText}>{iconMap[category.icon ?? ''] ?? '•'}</Text></View><View style={styles.cardBody}><Text style={styles.cardName}>{category.name}</Text><Text style={styles.meta}>{category.isDefault ? 'Default' : 'Custom'} · {category.isActive ? 'Active' : 'Inactive'}</Text></View>{!category.isDefault && <View style={styles.actions}>{category.isActive ? <Pressable onPress={onEdit}><Text style={styles.action}>Edit</Text></Pressable> : null}<Pressable onPress={onToggle}><Text style={styles.action}>{category.isActive ? 'Deactivate' : 'Restore'}</Text></Pressable></View>}</View>; }
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.filter, active && styles.filterActive]} onPress={onPress}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></Pressable>; }
function CategoryModal({ mode, category, onClose, onSaved }: { mode: 'create' | 'edit'; category?: Category; onClose: () => void; onSaved: () => void }) { const mutation = useMutation({ mutationFn: (input: FormValues) => mode === 'edit' && category ? categoryApi.update(category.id, input) : categoryApi.create(input), onSuccess: onSaved }); const { register, handleSubmit, setValue, watch, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { name: category?.name ?? '', type: category?.type ?? 'EXPENSE', icon: category?.icon ?? '' } }); const selectedType = watch('type'); return <Modal transparent animationType="slide" visible onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.modal}><Text style={styles.modalTitle}>{mode === 'edit' ? 'Edit Category' : 'Add Category'}</Text><TextInput style={styles.input} placeholder="Category Name" defaultValue={category?.name ?? ''} onChangeText={(value) => setValue('name', value, { shouldValidate: true })} {...register('name')} />{errors.name && <Text style={styles.error}>{errors.name.message}</Text>}<Text style={styles.modalLabel}>Type</Text><View style={styles.filters}><Filter label="Income" active={selectedType === 'INCOME'} onPress={() => setValue('type', 'INCOME', { shouldValidate: true })} /><Filter label="Expense" active={selectedType === 'EXPENSE'} onPress={() => setValue('type', 'EXPENSE', { shouldValidate: true })} /></View><TextInput style={styles.input} placeholder="Icon identifier, e.g. dumbbell" defaultValue={category?.icon ?? ''} onChangeText={(value) => setValue('icon', value, { shouldValidate: true })} {...register('icon')} />{errors.icon && <Text style={styles.error}>{errors.icon.message}</Text>}<View style={styles.modalActions}><Pressable style={styles.cancel} onPress={onClose}><Text>Cancel</Text></Pressable><Pressable style={styles.save} onPress={handleSubmit((values) => mutation.mutate(values))} disabled={isSubmitting || mutation.isPending}><Text style={styles.saveText}>{mutation.isPending ? 'Saving…' : 'Save'}</Text></Pressable></View></View></View></Modal>; }
const styles = StyleSheet.create({ container: { backgroundColor: colors.background, padding: 20, paddingBottom: 40 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 }, eyebrow: { color: colors.secondary, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.navy, fontSize: 30, fontWeight: '700', marginTop: 4 }, addButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 14, height: 48, justifyContent: 'center', width: 48 }, addText: { color: '#fff', fontSize: 28 }, search: { backgroundColor: '#fff', borderColor: '#D9E2EC', borderRadius: 12, borderWidth: 1, padding: 14 }, filters: { flexDirection: 'row', gap: 8, marginVertical: 16 }, filter: { borderColor: '#D9E2EC', borderRadius: 10, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9 }, filterActive: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { color: colors.navy, fontWeight: '600' }, filterTextActive: { color: '#fff' }, card: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, flexDirection: 'row', marginBottom: 10, padding: 14 }, inactive: { opacity: 0.55 }, icon: { alignItems: 'center', borderRadius: 12, height: 44, justifyContent: 'center', width: 44 }, income: { backgroundColor: '#D1FADF' }, expense: { backgroundColor: '#FEE4E2' }, iconText: { color: colors.navy, fontSize: 20, fontWeight: '700' }, cardBody: { flex: 1, marginLeft: 12 }, cardName: { color: colors.navy, fontSize: 16, fontWeight: '700' }, meta: { color: '#667085', fontSize: 12, marginTop: 4 }, actions: { alignItems: 'flex-end', gap: 8 }, action: { color: colors.primary, fontSize: 12, fontWeight: '700' }, empty: { color: '#667085', paddingVertical: 42, textAlign: 'center' }, error: { color: '#B42318', fontSize: 13, marginTop: 6 }, modalBackdrop: { backgroundColor: '#04172A99', flex: 1, justifyContent: 'flex-end' }, modal: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24 }, modalTitle: { color: colors.navy, fontSize: 24, fontWeight: '700', marginBottom: 18 }, modalLabel: { color: colors.navy, fontWeight: '600', marginTop: 16 }, input: { borderColor: '#D9E2EC', borderRadius: 12, borderWidth: 1, marginTop: 12, padding: 14 }, modalActions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end', marginTop: 22 }, cancel: { borderColor: '#D9E2EC', borderRadius: 10, borderWidth: 1, padding: 13 }, save: { backgroundColor: colors.primary, borderRadius: 10, padding: 13 }, saveText: { color: '#fff', fontWeight: '700' } });
