import { zodResolver } from '@hookform/resolvers/zod';
import { router } from 'expo-router';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { z } from 'zod';
import { authApi } from '../../src/api/auth.api';
import { colors } from '../../src/constants/theme';
import { logout, setUser } from '../../src/store/slices/authSlice';
import { useAppDispatch, useAppSelector } from '../../src/store/store';

const editSchema = z.object({ name: z.string().min(2, 'Fadlan geli magacaaga.'), phone: z.string().optional() });
type EditValues = z.infer<typeof editSchema>;

export default function ProfileScreen() {
  const dispatch = useAppDispatch(); const user = useAppSelector((state) => state.auth.user); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const { register, handleSubmit, setValue, formState: { errors, isSubmitting } } = useForm<EditValues>({ resolver: zodResolver(editSchema), values: { name: user?.name ?? '', phone: user?.phone ?? '' } });
  if (!user) return null;
  async function save(values: EditValues) { try { const updated = await authApi.updateProfile(values); dispatch(setUser(updated)); setEditing(false); setMessage('Profile-ka waa la cusboonaysiiyay.'); } catch (err) { setError(err instanceof Error ? err.message : 'Profile-ka lama cusboonaysiin.'); } }
  async function updatePreference(input: { preferredLanguage?: 'SO' | 'EN'; preferredCurrency?: 'USD' | 'SOS' }) { try { const updated = await authApi.updateProfile(input); dispatch(setUser(updated)); setMessage('Preference-ka waa la cusboonaysiiyay.'); } catch (err) { setError(err instanceof Error ? err.message : 'Preference-ka lama cusboonaysiin.'); } }
  function deactivate() { Alert.alert('Deactivate account', 'Ma hubtaa inaad rabto inaad deactivate-gareyso account-kaaga? Diiwaannada maaliyadeed waa la ilaalinayaa.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Deactivate', style: 'destructive', onPress: async () => { await authApi.deactivateAccount(); await dispatch(logout()); router.replace('/(auth)/login'); } }]); }
  return <ScrollView contentContainerStyle={styles.container}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.slice(0, 1).toUpperCase()}</Text></View><Text style={styles.name}>{user.name}</Text><Text style={styles.email}>{user.email}</Text>{message && <Text style={styles.success}>{message}</Text>}{error && <Text style={styles.error}>{error}</Text>}<Section title="Account">{editing ? <><TextInput style={styles.input} placeholder="Name" defaultValue={user.name} onChangeText={(value) => setValue('name', value, { shouldValidate: true })} {...register('name')} /><TextInput style={styles.input} placeholder="Phone" defaultValue={user.phone ?? ''} onChangeText={(value) => setValue('phone', value, { shouldValidate: true })} {...register('phone')} />{errors.name && <Text style={styles.error}>{errors.name.message}</Text>}<Pressable style={styles.button} onPress={handleSubmit(save)} disabled={isSubmitting}><Text style={styles.buttonText}>{isSubmitting ? 'Saving…' : 'Save Changes'}</Text></Pressable></> : <><Info label="Phone" value={user.phone || 'Not set'} /><Info label="Role" value={user.role} /><Info label="Member since" value={new Date(user.createdAt).toLocaleDateString()} /><Pressable style={styles.secondaryButton} onPress={() => setEditing(true)}><Text style={styles.secondaryText}>Edit Profile</Text></Pressable></>}</Section><Section title="Preferences"><Text style={styles.label}>Language</Text><View style={styles.row}><Choice label="Somali" active={user.preferredLanguage === 'SO'} onPress={() => updatePreference({ preferredLanguage: 'SO' })} /><Choice label="English" active={user.preferredLanguage === 'EN'} onPress={() => updatePreference({ preferredLanguage: 'EN' })} /></View><Text style={styles.label}>Currency</Text><View style={styles.row}><Choice label="USD" active={user.preferredCurrency === 'USD'} onPress={() => updatePreference({ preferredCurrency: 'USD' })} /><Choice label="SOS" active={user.preferredCurrency === 'SOS'} onPress={() => updatePreference({ preferredCurrency: 'SOS' })} /></View></Section><Section title="Security"><Pressable style={styles.secondaryButton} onPress={() => router.push('/(auth)/forgot')}><Text style={styles.secondaryText}>Reset Password</Text></Pressable></Section><Section title="Danger Zone"><Pressable style={styles.dangerButton} onPress={deactivate}><Text style={styles.dangerText}>Deactivate Account</Text></Pressable><Pressable style={styles.secondaryButton} onPress={async () => { await dispatch(logout()); router.replace('/(auth)/login'); }}><Text style={styles.secondaryText}>Logout</Text></Pressable></Section></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.choice, active && styles.choiceActive]} onPress={onPress}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ container: { backgroundColor: colors.background, padding: 24, paddingBottom: 48 }, avatar: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.secondary, borderRadius: 42, height: 84, justifyContent: 'center', width: 84 }, avatarText: { color: '#fff', fontSize: 36, fontWeight: '700' }, name: { color: colors.navy, fontSize: 26, fontWeight: '700', marginTop: 14, textAlign: 'center' }, email: { color: '#52606D', marginTop: 4, textAlign: 'center' }, section: { backgroundColor: '#fff', borderRadius: 18, marginTop: 20, padding: 18 }, sectionTitle: { color: colors.navy, fontSize: 18, fontWeight: '700', marginBottom: 14 }, info: { borderBottomColor: '#EEF2F6', borderBottomWidth: 1, paddingVertical: 10 }, label: { color: '#52606D', fontSize: 13, marginBottom: 6 }, value: { color: colors.navy, fontSize: 16, fontWeight: '600' }, input: { borderColor: '#D9E2EC', borderRadius: 12, borderWidth: 1, marginBottom: 10, padding: 13 }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, marginTop: 8, padding: 14 }, buttonText: { color: '#fff', fontWeight: '700' }, secondaryButton: { alignItems: 'center', borderColor: '#D9E2EC', borderRadius: 12, borderWidth: 1, marginTop: 12, padding: 13 }, secondaryText: { color: colors.navy, fontWeight: '700' }, row: { flexDirection: 'row', gap: 10, marginBottom: 16 }, choice: { borderColor: '#D9E2EC', borderRadius: 10, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 10 }, choiceActive: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.navy, fontWeight: '600' }, choiceTextActive: { color: '#fff' }, dangerButton: { alignItems: 'center', borderColor: '#FDA29B', borderRadius: 12, borderWidth: 1, marginTop: 4, padding: 13 }, dangerText: { color: '#B42318', fontWeight: '700' }, success: { color: '#027A48', marginTop: 16, textAlign: 'center' }, error: { color: '#B42318', marginTop: 8 } });
