import { Request, Response } from 'express';
import { getPrismaClient } from '../../config/prisma';
import { answerWithFinancialData } from './ai.service';
import { aiChatSchema, aiConversationIdSchema, aiConversationQuerySchema } from '../../validators/ai.validator';
function errorResponse(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function id(req: Request) { return typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; }
export async function chat(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = aiChatSchema.safeParse(req.body); if (!parsed.success) return errorResponse(res, parsed.error); const prisma = getPrismaClient(); let conversationId = parsed.data.conversationId; if (conversationId) { const owned = await prisma.aIConversation.findFirst({ where: { id: conversationId, userId: req.user.id }, select: { id: true } }); if (!owned) return res.status(404).json({ success: false, message: 'Conversation not found.' }); } else { const created = await prisma.aIConversation.create({ data: { userId: req.user.id, title: parsed.data.message.slice(0, 80) }, select: { id: true } }); conversationId = created.id; } const prior = await prisma.aIMessage.findMany({ where: { conversationId, role: { in: ['USER', 'ASSISTANT'] } }, orderBy: { createdAt: 'desc' }, take: 8, select: { role: true, content: true } }); const history = prior.reverse().map((message) => ({ role: message.role === 'USER' ? 'user' as const : 'assistant' as const, content: message.content })); await prisma.aIMessage.create({ data: { conversationId, role: 'USER', content: parsed.data.message } }); try { const result = await answerWithFinancialData(req.user.id, parsed.data.message, history); const assistant = await prisma.aIMessage.create({ data: { conversationId, role: 'ASSISTANT', content: result.answer } }); await prisma.aIConversation.update({ where: { id: conversationId }, data: { updatedAt: new Date() } }); return res.status(201).json({ success: true, message: 'AI response generated successfully.', data: { message: result.answer, conversationId, sources: [result.source], assistantMessageId: assistant.id } }); } catch (error) { return res.status(502).json({ success: false, message: error instanceof Error ? error.message : 'AI provider unavailable.' }); } }
export async function listConversations(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = aiConversationQuerySchema.safeParse(req.query); if (!parsed.success) return errorResponse(res, parsed.error); const [data, total] = await getPrismaClient().$transaction([getPrismaClient().aIConversation.findMany({ where: { userId: req.user.id }, orderBy: { updatedAt: 'desc' }, skip: (parsed.data.page - 1) * parsed.data.limit, take: parsed.data.limit, select: { id: true, title: true, createdAt: true, updatedAt: true, _count: { select: { messages: true } } } }), getPrismaClient().aIConversation.count({ where: { userId: req.user.id } })]); return res.json({ success: true, message: 'AI conversations retrieved successfully.', data, pagination: { page: parsed.data.page, limit: parsed.data.limit, total, totalPages: Math.ceil(total / parsed.data.limit) } }); }
export async function getConversation(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = aiConversationIdSchema.safeParse({ id: id(req) }); if (!parsed.success) return errorResponse(res, parsed.error); const conversation = await getPrismaClient().aIConversation.findFirst({ where: { id: parsed.data.id, userId: req.user.id }, select: { id: true, title: true, createdAt: true, updatedAt: true } }); if (!conversation) return res.status(404).json({ success: false, message: 'Conversation not found.' }); return res.json({ success: true, message: 'Conversation retrieved successfully.', data: conversation }); }
export async function getMessages(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const conversationId = id(req); const owned = await getPrismaClient().aIConversation.findFirst({ where: { id: conversationId, userId: req.user.id }, select: { id: true } }); if (!owned) return res.status(404).json({ success: false, message: 'Conversation not found.' }); const messages = await getPrismaClient().aIMessage.findMany({ where: { conversationId }, orderBy: { createdAt: 'asc' }, select: { id: true, role: true, content: true, createdAt: true } }); return res.json({ success: true, message: 'Conversation messages retrieved successfully.', data: messages }); }
export async function deleteConversation(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const result = await getPrismaClient().aIConversation.deleteMany({ where: { id: id(req), userId: req.user.id } }); if (!result.count) return res.status(404).json({ success: false, message: 'Conversation not found.' }); return res.json({ success: true, message: 'Conversation deleted successfully.' }); }
