import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../../config/prisma';
import { budgetReport, currencies, goalsReport, overviewRows, recurringReport, resolvePeriod, savingsReport, spendingAnalysis, transactions, trendRows } from '../../services/report.service';

type ToolContext = { userId: string; message: string };
const queryFor = (message: string) => { const lower = message.toLowerCase(); const period = lower.includes('last month') || lower.includes('bishii hore') ? 'LAST_MONTH' : lower.includes('this year') || lower.includes('sanadkan') ? 'THIS_YEAR' : lower.includes('today') || lower.includes('maanta') ? 'TODAY' : lower.includes('this week') || lower.includes('usbuucan') ? 'THIS_WEEK' : 'THIS_MONTH'; const currency = lower.includes('sos') || lower.includes('shilin') ? 'SOS' : lower.includes('usd') || lower.includes('dollar') || lower.includes('$') ? 'USD' : undefined; return { period, currency, months: 6 } as const; };
const periodFor = (message: string) => resolvePeriod(queryFor(message));

export async function getFinancialOverview({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const data = overviewRows(await transactions(userId, period, query.currency)); const savings = await savingsReport(userId, period, query.currency); return { tool: 'getFinancialOverview', period: query.period, currency: query.currency ?? 'USD and SOS separately', overview: data, savings }; }
export async function getIncomeData({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const rows = await transactions(userId, period, query.currency); return { tool: 'getIncomeData', period: query.period, data: overviewRows(rows), incomeByMonth: Object.fromEntries(currencies(query.currency).map((c) => [c, trendRows(rows.filter((r) => r.currency === c && r.type === 'INCOME'), period, 'month')])) }; }
export async function getExpenseData({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const rows = await transactions(userId, period, query.currency); return { tool: 'getExpenseData', period: query.period, data: overviewRows(rows), spending: Object.fromEntries(currencies(query.currency).map((c) => [c, spendingAnalysis(rows.filter((r) => r.currency === c), period)])) }; }
export async function getCategorySpending({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const rows = await transactions(userId, period, query.currency); return { tool: 'getCategorySpending', period: query.period, categories: Object.fromEntries(currencies(query.currency).map((c) => [c, spendingAnalysis(rows.filter((r) => r.currency === c), period).topCategories])) }; }
export async function getBudgetStatus({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); return { tool: 'getBudgetStatus', budgets: await budgetReport(userId, period, query.currency) }; }
export async function getSavingsStatus({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const plans = await getPrismaClient().savings.findMany({ where: { userId, ...(query.currency ? { currency: query.currency } : {}) }, select: { name: true, targetAmount: true, currentAmount: true, currency: true, isActive: true, targetDate: true } }); return { tool: 'getSavingsStatus', plans: plans.map((p) => ({ name: p.name, target: p.targetAmount.toString(), saved: p.currentAmount.toString(), remaining: Prisma.Decimal.max(new Prisma.Decimal(0), p.targetAmount.minus(p.currentAmount)).toString(), progress: p.targetAmount.isZero() ? 0 : Number(p.currentAmount.div(p.targetAmount).times(100).toFixed(2)), currency: p.currency, isActive: p.isActive, targetDate: p.targetDate.toISOString().slice(0, 10) })) }; }
export async function getGoalStatus({ userId, message }: ToolContext) { const query = queryFor(message); const goals = await getPrismaClient().financialGoal.findMany({ where: { userId, ...(query.currency ? { currency: query.currency } : {}) }, select: { name: true, targetAmount: true, currentAmount: true, currency: true, status: true, targetDate: true } }); return { tool: 'getGoalStatus', goals: goals.map((g) => ({ goalName: g.name, target: g.targetAmount.toString(), saved: g.currentAmount.toString(), remaining: Prisma.Decimal.max(new Prisma.Decimal(0), g.targetAmount.minus(g.currentAmount)).toString(), progress: g.targetAmount.isZero() ? 0 : Number(g.currentAmount.div(g.targetAmount).times(100).toFixed(2)), status: g.status, currency: g.currency, targetDate: g.targetDate.toISOString().slice(0, 10) })) }; }
export async function getRecurringTransactions({ userId, message }: ToolContext) { const query = queryFor(message); const schedules = await getPrismaClient().recurringTransaction.findMany({ where: { userId, ...(query.currency ? { currency: query.currency } : {}) }, select: { name: true, type: true, amount: true, currency: true, frequency: true, interval: true, nextRunDate: true, isActive: true, isPaused: true }, orderBy: { nextRunDate: 'asc' } }); return { tool: 'getRecurringTransactions', schedules: schedules.map((s) => ({ name: s.name, type: s.type, amount: s.amount.toString(), currency: s.currency, frequency: s.frequency, interval: s.interval, nextRunDate: s.nextRunDate.toISOString().slice(0, 10), status: !s.isActive ? 'INACTIVE' : s.isPaused ? 'PAUSED' : 'ACTIVE' })) }; }
export async function getFinancialTrends({ userId, message }: ToolContext) { const query = queryFor(message); const period = periodFor(message); const current = overviewRows(await transactions(userId, period, query.currency)); const previousPeriod = { start: period.previousStart, end: period.previousEnd, previousStart: period.previousStart, previousEnd: period.previousEnd }; const previous = overviewRows(await transactions(userId, previousPeriod, query.currency)); return { tool: 'getFinancialTrends', period: query.period, current, previous }; }
export function selectTool(message: string) { const lower = message.toLowerCase(); if (lower.includes('budget') || lower.includes('miisaan')) return getBudgetStatus; if (lower.includes('saving') || lower.includes('keyds') || lower.includes('kayd')) return getSavingsStatus; if (lower.includes('goal') || lower.includes('hadaf')) return getGoalStatus; if (lower.includes('recurring') || lower.includes('payment') || lower.includes('lacag bixin')) return getRecurringTransactions; if (lower.includes('trend') || lower.includes('compare') || lower.includes('barbardhig') || lower.includes('bishii hore')) return getFinancialTrends; if (lower.includes('income') || lower.includes('dakhli') || lower.includes('soo galay')) return getIncomeData; if (lower.includes('expense') || lower.includes('spend') || lower.includes('spent') || lower.includes('kharash') || lower.includes('baxay')) return lower.includes('category') || lower.includes('qayb') ? getCategorySpending : getExpenseData; return getFinancialOverview; }
