import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { processRecurringTransactions } from './recurringTransaction.service';
import { createBudgetNotification, createDebtNotification, createGoalNotification, createRecurringNotification, createSavingsNotification } from '../utils/notification.utils';

const dayKey = (date: Date) => date.toISOString().slice(0, 10);
const startOfDay = (date: Date) => new Date(`${dayKey(date)}T00:00:00.000Z`);
const addDays = (date: Date, days: number) => new Date(date.getTime() + days * 86400000);
const percent = (current: Prisma.Decimal, target: Prisma.Decimal) => target.isZero() ? 0 : Number(current.div(target).times(100).toFixed(2));

export async function processNotificationReminders(userId?: string, asOf = new Date()) { const prisma = getPrismaClient(); const today = startOfDay(asOf); let created = 0; let evaluated = 0; let recurringGenerated = 0;
  const budgets = await prisma.budget.findMany({ where: { ...(userId ? { userId } : {}), isActive: true }, select: { id: true, userId: true, categoryId: true, name: true, amount: true, currency: true, startDate: true, endDate: true, category: { select: { name: true } } } });
  for (const budget of budgets) { const spent = await prisma.transaction.aggregate({ where: { userId: budget.userId, categoryId: budget.categoryId ?? undefined, type: 'EXPENSE', currency: budget.currency, isDeleted: false, date: { gte: budget.startDate, lte: budget.endDate } }, _sum: { amount: true } }); const ratio = percent(spent._sum.amount ?? new Prisma.Decimal(0), budget.amount); const threshold = ratio >= 100 ? 100 : ratio >= 90 ? 90 : ratio >= 70 ? 70 : 0; if (threshold) { evaluated += 1; const type = threshold >= 100 ? 'BUDGET_EXCEEDED' : 'BUDGET_WARNING'; const notification = await createBudgetNotification(budget.userId, type, threshold >= 100 ? 'Budget exceeded' : 'Budget warning', `${budget.category?.name ?? budget.name} budget has reached ${threshold}%.`, budget.id, `budget:${budget.id}:${dayKey(budget.startDate)}:threshold:${threshold}`); if (notification) created += 1; } }
  const savings = await prisma.savings.findMany({ where: { ...(userId ? { userId } : {}) }, select: { id: true, userId: true, name: true, currentAmount: true, targetAmount: true, currency: true } });
  for (const plan of savings) { const ratio = percent(plan.currentAmount, plan.targetAmount); const threshold = ratio >= 100 ? 100 : ratio >= 80 ? 80 : ratio >= 50 ? 50 : 0; if (threshold) { evaluated += 1; const type = threshold === 100 ? 'SAVINGS_COMPLETED' : 'SAVINGS_PROGRESS'; const notification = await createSavingsNotification(plan.userId, type, threshold === 100 ? 'Savings completed' : 'Savings progress', threshold === 100 ? `Congratulations! You completed ${plan.name}.` : `You have reached ${threshold}% of ${plan.name}.`, plan.id, `savings:${plan.id}:milestone:${threshold}`); if (notification) created += 1; } }
  const goals = await prisma.financialGoal.findMany({ where: { ...(userId ? { userId } : {}), isActive: true }, select: { id: true, userId: true, name: true, currentAmount: true, targetAmount: true, targetDate: true, status: true } });
  for (const goal of goals) { const ratio = percent(goal.currentAmount, goal.targetAmount); const threshold = ratio >= 100 ? 100 : ratio >= 80 ? 80 : ratio >= 50 ? 50 : 0; if (threshold) { evaluated += 1; const type = threshold === 100 ? 'GOAL_COMPLETED' : 'GOAL_PROGRESS'; const notification = await createGoalNotification(goal.userId, type, threshold === 100 ? 'Goal completed' : 'Goal progress', threshold === 100 ? `Congratulations! You completed ${goal.name}.` : `You have reached ${threshold}% of ${goal.name}.`, goal.id, `goal:${goal.id}:milestone:${threshold}`); if (notification) created += 1; } if (goal.currentAmount.lessThan(goal.targetAmount)) { const days = Math.ceil((startOfDay(goal.targetDate).getTime() - today.getTime()) / 86400000); if ([7, 3, 1].includes(days)) { evaluated += 1; const notification = await createGoalNotification(goal.userId, 'GOAL_DEADLINE', 'Goal deadline approaching', `${goal.name} is due in ${days} day${days === 1 ? '' : 's'}.`, goal.id, `goal:${goal.id}:deadline:${dayKey(goal.targetDate)}:${days}`); if (notification) created += 1; } } }
  const debts = await prisma.debt.findMany({ where: { ...(userId ? { userId } : {}), isDeleted: false, status: { in: ['ACTIVE', 'PARTIALLY_PAID', 'OVERDUE'] }, dueDate: { not: null } }, select: { id: true, userId: true, personName: true, title: true, currency: true, remainingAmount: true, dueDate: true, status: true } });
  for (const debt of debts) { if (!debt.dueDate || debt.remainingAmount.isZero()) continue; const days = Math.ceil((startOfDay(debt.dueDate).getTime() - today.getTime()) / 86400000); if ([7, 3, 1].includes(days)) { evaluated += 1; const notification = await createDebtNotification(debt.userId, 'DEBT_DUE_SOON', 'Debt due soon', `${debt.title} with ${debt.personName} is due in ${days} day${days === 1 ? '' : 's'}.`, debt.id, `debt:${debt.id}:due:${dayKey(debt.dueDate)}:${days}`); if (notification) created += 1; } if (days < 0) { evaluated += 1; const notification = await createDebtNotification(debt.userId, 'DEBT_OVERDUE', 'Debt overdue', `${debt.title} with ${debt.personName} is overdue. Remaining: ${debt.currency} ${debt.remainingAmount.toString()}.`, debt.id, `debt:${debt.id}:overdue:${dayKey(debt.dueDate)}`); if (notification) created += 1; } }
  const upcomingDate = dayKey(addDays(today, 1)); const recurring = await prisma.recurringTransaction.findMany({ where: { ...(userId ? { userId } : {}), isActive: true, isPaused: false, nextRunDate: { gte: addDays(today, 1), lt: addDays(today, 2) } }, select: { id: true, userId: true, name: true, amount: true, currency: true } }); for (const schedule of recurring) { evaluated += 1; const notification = await createRecurringNotification(schedule.userId, 'RECURRING_UPCOMING', 'Recurring transaction tomorrow', `${schedule.name} for ${schedule.currency} ${schedule.amount.toString()} is scheduled for tomorrow.`, schedule.id, `recurring:${schedule.id}:upcoming:${upcomingDate}`); if (notification) created += 1; }
  if (userId) { const result = await processRecurringTransactions(userId, asOf); recurringGenerated = result.generated; }
  return { evaluated, created, recurringGenerated, asOf: asOf.toISOString() }; }

export async function processDebtNotifications(userId?: string, asOf = new Date()) { const prisma = getPrismaClient(); const today = startOfDay(asOf); const debts = await prisma.debt.findMany({ where: { ...(userId ? { userId } : {}), isDeleted: false, status: { in: ['ACTIVE', 'PARTIALLY_PAID', 'OVERDUE'] }, dueDate: { not: null } }, select: { id: true, userId: true, personName: true, title: true, currency: true, remainingAmount: true, dueDate: true } }); let created = 0; for (const debt of debts) { if (!debt.dueDate || debt.remainingAmount.isZero()) continue; const days = Math.ceil((startOfDay(debt.dueDate).getTime() - today.getTime()) / 86400000); if ([7, 3, 1].includes(days)) { const notification = await createDebtNotification(debt.userId, 'DEBT_DUE_SOON', 'Debt due soon', `${debt.title} with ${debt.personName} is due in ${days} day${days === 1 ? '' : 's'}.`, debt.id, `debt:${debt.id}:due:${dayKey(debt.dueDate)}:${days}`); if (notification) created += 1; } else if (days < 0) { const notification = await createDebtNotification(debt.userId, 'DEBT_OVERDUE', 'Debt overdue', `${debt.title} with ${debt.personName} is overdue. Remaining: ${debt.currency} ${debt.remainingAmount.toString()}.`, debt.id, `debt:${debt.id}:overdue:${dayKey(debt.dueDate)}`); if (notification) created += 1; } } return { evaluated: debts.length, created, asOf: asOf.toISOString() }; }
