import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env";
import healthRoutes from "./routes/health.routes";
import authRoutes from "./routes/auth.routes";
import userRoutes from "./routes/user.routes";
import adminRoutes from "./routes/admin.routes";
import categoryRoutes from "./routes/category.routes";
import adminCategoryRoutes from "./routes/admin-category.routes";
import transactionRoutes from "./routes/transaction.routes";
import adminTransactionRoutes from "./routes/admin-transaction.routes";
import budgetRoutes from "./routes/budget.routes";
import adminBudgetRoutes from "./routes/admin-budget.routes";
import { errorHandler, notFound } from "./middleware/errorHandler";
const app = express();
app.use(helmet());
app.use(cors({ origin: env.corsOrigin === "*" ? true : env.corsOrigin }));
app.use(express.json());
app.use(morgan("dev"));
app.use("/api/v1", healthRoutes);
app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/users", userRoutes);
app.use("/api/v1/admin", adminRoutes);
app.use("/api/v1/categories", categoryRoutes);
app.use("/api/v1/admin/categories", adminCategoryRoutes);
app.use("/api/v1/transactions", transactionRoutes);
app.use("/api/v1/admin/transactions", adminTransactionRoutes);
app.use("/api/v1/budgets", budgetRoutes);
app.use("/api/v1/admin/budgets", adminBudgetRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
