import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env";
import healthRoutes from "./routes/health.routes";
import { errorHandler, notFound } from "./middleware/errorHandler";
const app = express();
app.use(helmet());
app.use(cors({ origin: env.corsOrigin === "*" ? true : env.corsOrigin }));
app.use(express.json());
app.use(morgan("dev"));
app.use("/api/v1", healthRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
