import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env";
import healthRoutes from "./routes/health.routes";
import authRoutes from "./routes/auth.routes";
import userRoutes from "./routes/user.routes";
import adminRoutes from "./routes/admin.routes";
import categoryRoutes from "./routes/category.routes";
import adminCategoryRoutes from "./routes/admin-category.routes";
import transactionRoutes from "./routes/transaction.routes";
import adminTransactionRoutes from "./routes/admin-transaction.routes";
import budgetRoutes from "./routes/budget.routes";
import adminBudgetRoutes from "./routes/admin-budget.routes";
import savingsRoutes from "./routes/savings.routes";
import adminSavingsRoutes from "./routes/admin-savings.routes";
import financialGoalRoutes from "./routes/financialGoal.routes";
import adminFinancialGoalRoutes from "./routes/admin-financialGoal.routes";
import recurringTransactionRoutes from "./routes/recurringTransaction.routes";
import adminRecurringTransactionRoutes from "./routes/admin-recurringTransaction.routes";
import notificationRoutes from "./routes/notification.routes";
import adminNotificationRoutes from "./routes/admin-notification.routes";
import reportRoutes from "./routes/report.routes";
import adminReportRoutes from "./routes/admin-report.routes";
import aiRoutes from "./modules/ai/ai.routes";
import debtRoutes from "./routes/debt.routes";
import adminDebtRoutes from "./routes/admin-debt.routes";
import { errorHandler, notFound } from "./middleware/errorHandler";
const app = express();
app.use(helmet());
app.use(cors({ origin: env.corsOrigin === "*" ? true : env.corsOrigin }));
app.use(express.json());
app.use(morgan("dev"));
app.use("/api/v1", healthRoutes);
app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/users", userRoutes);
app.use("/api/v1/admin", adminRoutes);
app.use("/api/v1/categories", categoryRoutes);
app.use("/api/v1/admin/categories", adminCategoryRoutes);
app.use("/api/v1/transactions", transactionRoutes);
app.use("/api/v1/admin/transactions", adminTransactionRoutes);
app.use("/api/v1/budgets", budgetRoutes);
app.use("/api/v1/admin/budgets", adminBudgetRoutes);
app.use("/api/v1/savings", savingsRoutes);
app.use("/api/v1/admin/savings", adminSavingsRoutes);
app.use("/api/v1/goals", financialGoalRoutes);
app.use("/api/v1/admin/goals", adminFinancialGoalRoutes);
app.use("/api/v1/recurring-transactions", recurringTransactionRoutes);
app.use("/api/v1/admin/recurring-transactions", adminRecurringTransactionRoutes);
app.use("/api/v1/notifications", notificationRoutes);
app.use("/api/v1/admin/notifications", adminNotificationRoutes);
app.use("/api/v1/reports", reportRoutes);
app.use("/api/v1/admin/reports", adminReportRoutes);
app.use("/api/v1/ai", aiRoutes);
app.use("/api/v1/debts", debtRoutes);
app.use("/api/v1/admin/debts", adminDebtRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
