import type { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { budgetQuerySchema, budgetSummaryQuerySchema, createBudgetSchema, updateBudgetSchema, type BudgetInput } from '../validators/budget.validator';

const budgetSelect = { id: true, name: true, amount: true, currency: true, startDate: true, endDate: true, isActive: true, createdAt: true, updatedAt: true, category: { select: { id: true, name: true, type: true, icon: true } } } as const;
function dateAtStart(value: string) { return new Date(`${value}T00:00:00.000Z`); }
function dateAtEnd(value: string) { return new Date(`${value}T23:59:59.999Z`); }
function dateOnly(value: Date) { return value.toISOString().slice(0, 10); }
function errorResponse(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function statusFor(percentage: Prisma.Decimal) { if (percentage.greaterThanOrEqualTo(100)) return 'EXCEEDED'; if (percentage.greaterThanOrEqualTo(90)) return 'NEAR_LIMIT'; if (percentage.greaterThanOrEqualTo(70)) return 'WARNING'; return 'SAFE'; }
async function accessibleExpenseCategory(userId: string, categoryId: string) { return getPrismaClient().category.findFirst({ where: { id: categoryId, type: 'EXPENSE', isActive: true, OR: [{ isDefault: true }, { userId }] }, select: { id: true, type: true } }); }
async function hasOverlap(userId: string, categoryId: string, currency: 'USD' | 'SOS', startDate: Date, endDate: Date, excludeId?: string) { return getPrismaClient().budget.findFirst({ where: { userId, categoryId, currency, isActive: true, startDate: { lte: endDate }, endDate: { gte: startDate }, ...(excludeId ? { NOT: { id: excludeId } } : {}) }, select: { id: true } }); }
type BudgetForSnapshot = { amount: Prisma.Decimal; currency: 'USD' | 'SOS'; startDate: Date; endDate: Date; userId: string; categoryId: string | null; [key: string]: unknown };
async function snapshot(budget: BudgetForSnapshot) { const spentRow = await getPrismaClient().transaction.aggregate({ where: { userId: budget.userId, categoryId: budget.categoryId ?? undefined, type: 'EXPENSE', currency: budget.currency, isDeleted: false, date: { gte: budget.startDate, lte: budget.endDate } }, _sum: { amount: true } }); const spent = spentRow._sum.amount ?? new Prisma.Decimal(0); const remaining = budget.amount.minus(spent); const percentage = budget.amount.isZero() ? new Prisma.Decimal(0) : spent.div(budget.amount).times(100); return { budgetAmount: budget.amount.toString(), spentAmount: spent.toString(), remainingAmount: remaining.toString(), percentageUsed: Number(percentage.toFixed(2)), status: statusFor(percentage) }; }
async function withSnapshot(budget: BudgetForSnapshot) { const { amount: _amount, userId: _userId, ...rest } = budget; return { ...rest, ...(await snapshot(budget)) }; }
async function validateInput(userId: string, input: BudgetInput) { const category = await accessibleExpenseCategory(userId, input.categoryId); if (!category) return { error: 'Budget category must be an active accessible expense category.' } as const; const startDate = dateAtStart(input.startDate); const endDate = dateAtEnd(input.endDate); return { startDate, endDate, category } as const; }

export async function createBudget(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = createBudgetSchema.safeParse(req.body); if (!parsed.success) return errorResponse(res, parsed.error); const checked = await validateInput(req.user.id, parsed.data); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); if (await hasOverlap(req.user.id, parsed.data.categoryId, parsed.data.currency, checked.startDate, checked.endDate)) return res.status(409).json({ success: false, message: 'A budget already exists for this category during the selected period.' }); const start = checked.startDate; const budget = await getPrismaClient().budget.create({ data: { userId: req.user.id, categoryId: parsed.data.categoryId, name: parsed.data.name.trim(), amount: new Prisma.Decimal(parsed.data.amount), currency: parsed.data.currency, startDate: start, endDate: checked.endDate, month: start.getUTCMonth() + 1, year: start.getUTCFullYear(), isActive: true }, select: budgetSelect }); return res.status(201).json({ success: true, message: 'Budget created successfully', data: await withSnapshot({ ...budget, userId: req.user.id, categoryId: parsed.data.categoryId }) }); }

export async function getBudgets(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = budgetQuerySchema.safeParse(req.query); if (!parsed.success) return errorResponse(res, parsed.error); const filters = parsed.data; const budgets = await getPrismaClient().budget.findMany({ where: { userId: req.user.id, ...(filters.categoryId ? { categoryId: filters.categoryId } : {}), ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { name: { contains: filters.search, mode: 'insensitive' as const } } : {}) }, select: { ...budgetSelect, userId: true, categoryId: true }, orderBy: { startDate: 'desc' } }); const enriched = await Promise.all(budgets.map((budget) => withSnapshot(budget))); const filtered = filters.status ? enriched.filter((budget) => budget.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; const data = filtered.slice(start, start + filters.limit); return res.json({ success: true, message: 'Budgets retrieved successfully', data, pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getBudgetById(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const budget = await getPrismaClient().budget.findFirst({ where: { id, userId: req.user.id }, select: { ...budgetSelect, userId: true, categoryId: true } }); if (!budget) return res.status(404).json({ success: false, message: 'Budget not found.' }); const recentTransactions = await getPrismaClient().transaction.findMany({ where: { userId: req.user.id, categoryId: budget.categoryId ?? undefined, type: 'EXPENSE', currency: budget.currency, isDeleted: false, date: { gte: budget.startDate, lte: budget.endDate } }, select: { id: true, amount: true, currency: true, description: true, date: true }, orderBy: { date: 'desc' }, take: 10 }); return res.json({ success: true, message: 'Budget retrieved successfully', data: { ...(await withSnapshot(budget)), recentTransactions: recentTransactions.map((transaction) => ({ ...transaction, amount: transaction.amount.toString() })) } }); }

export async function updateBudget(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const parsed = updateBudgetSchema.safeParse(req.body); if (!parsed.success) return errorResponse(res, parsed.error); const existing = await getPrismaClient().budget.findFirst({ where: { id, userId: req.user.id }, select: { id: true } }); if (!existing) return res.status(404).json({ success: false, message: 'Budget not found.' }); const checked = await validateInput(req.user.id, parsed.data); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); if (await hasOverlap(req.user.id, parsed.data.categoryId, parsed.data.currency, checked.startDate, checked.endDate, id)) return res.status(409).json({ success: false, message: 'A budget already exists for this category during the selected period.' }); const budget = await getPrismaClient().budget.update({ where: { id }, data: { name: parsed.data.name.trim(), categoryId: parsed.data.categoryId, amount: new Prisma.Decimal(parsed.data.amount), currency: parsed.data.currency, startDate: checked.startDate, endDate: checked.endDate, month: checked.startDate.getUTCMonth() + 1, year: checked.startDate.getUTCFullYear() }, select: budgetSelect }); return res.json({ success: true, message: 'Budget updated successfully', data: await withSnapshot({ ...budget, userId: req.user.id, categoryId: parsed.data.categoryId }) }); }

export async function deactivateBudget(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const result = await getPrismaClient().budget.updateMany({ where: { id, userId: req.user.id, isActive: true }, data: { isActive: false } }); if (!result.count) return res.status(404).json({ success: false, message: 'Budget not found.' }); return res.json({ success: true, message: 'Budget deactivated successfully' }); }

export async function restoreBudget(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const existing = await getPrismaClient().budget.findFirst({ where: { id, userId: req.user.id }, select: { id: true, categoryId: true, currency: true, startDate: true, endDate: true, isActive: true } }); if (!existing) return res.status(404).json({ success: false, message: 'Budget not found.' }); if (existing.isActive) return res.json({ success: true, message: 'Budget is already active.' }); if (!existing.categoryId || !(await accessibleExpenseCategory(req.user.id, existing.categoryId))) return res.status(409).json({ success: false, message: 'Budget category is no longer an active expense category.' }); if (await hasOverlap(req.user.id, existing.categoryId, existing.currency, existing.startDate, existing.endDate, id)) return res.status(409).json({ success: false, message: 'Another active budget overlaps this period.' }); const budget = await getPrismaClient().budget.update({ where: { id }, data: { isActive: true }, select: budgetSelect }); return res.json({ success: true, message: 'Budget restored successfully', data: await withSnapshot({ ...budget, userId: req.user.id, categoryId: existing.categoryId }) }); }

export async function getBudgetSummary(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = budgetSummaryQuerySchema.safeParse(req.query); if (!parsed.success) return errorResponse(res, parsed.error); const budgets = await getPrismaClient().budget.findMany({ where: { userId: req.user.id, ...(parsed.data.currency ? { currency: parsed.data.currency } : {}) }, select: { amount: true, currency: true, isActive: true, startDate: true, endDate: true, userId: true, categoryId: true } }); const summaries: Record<string, { totalBudgets: number; activeBudgets: number; totalBudgetedAmount: string; totalSpentAmount: string; totalRemainingAmount: string; budgetsExceeded: number; budgetsNearLimit: number }> = {}; for (const budget of budgets) { const unit = summaries[budget.currency] ?? { totalBudgets: 0, activeBudgets: 0, totalBudgetedAmount: '0', totalSpentAmount: '0', totalRemainingAmount: '0', budgetsExceeded: 0, budgetsNearLimit: 0 }; const result = await snapshot({ ...budget, id: '', amount: budget.amount }); unit.totalBudgets += 1; if (budget.isActive) unit.activeBudgets += 1; unit.totalBudgetedAmount = new Prisma.Decimal(unit.totalBudgetedAmount).plus(budget.amount).toString(); unit.totalSpentAmount = new Prisma.Decimal(unit.totalSpentAmount).plus(result.spentAmount).toString(); unit.totalRemainingAmount = new Prisma.Decimal(unit.totalRemainingAmount).plus(result.remainingAmount).toString(); if (result.status === 'EXCEEDED') unit.budgetsExceeded += 1; if (result.status === 'NEAR_LIMIT') unit.budgetsNearLimit += 1; summaries[budget.currency] = unit; } return res.json({ success: true, message: 'Budget summary retrieved successfully', data: summaries }); }

export async function listAdminBudgets(req: Request, res: Response) { const parsed = budgetQuerySchema.safeParse(req.query); if (!parsed.success) return errorResponse(res, parsed.error); const filters = parsed.data; const budgets = await getPrismaClient().budget.findMany({ where: { ...(filters.categoryId ? { categoryId: filters.categoryId } : {}), ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { name: { contains: filters.search, mode: 'insensitive' as const } } : {}) }, select: { ...budgetSelect, userId: true, categoryId: true, user: { select: { id: true, name: true, email: true } } }, orderBy: { startDate: 'desc' } }); const enriched = await Promise.all(budgets.map((budget) => withSnapshot(budget))); const filtered = filters.status ? enriched.filter((budget) => budget.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; return res.json({ success: true, message: 'Admin budgets retrieved successfully', data: filtered.slice(start, start + filters.limit), pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getAdminBudgetSummary(req: Request, res: Response) { const parsed = budgetSummaryQuerySchema.safeParse(req.query); if (!parsed.success) return errorResponse(res, parsed.error); const budgets = await getPrismaClient().budget.findMany({ where: parsed.data.currency ? { currency: parsed.data.currency } : {}, select: { amount: true, currency: true, isActive: true, startDate: true, endDate: true, userId: true, categoryId: true } }); const result: Record<string, { totalBudgets: number; activeBudgets: number; budgetsExceeded: number; budgetsNearLimit: number; totalBudgetedAmount: string; totalSpentAmount: string; totalRemainingAmount: string }> = {}; for (const budget of budgets) { const unit = result[budget.currency] ?? { totalBudgets: 0, activeBudgets: 0, budgetsExceeded: 0, budgetsNearLimit: 0, totalBudgetedAmount: '0', totalSpentAmount: '0', totalRemainingAmount: '0' }; const snapshotResult = await snapshot({ ...budget, id: '' }); unit.totalBudgets += 1; if (budget.isActive) unit.activeBudgets += 1; if (snapshotResult.status === 'EXCEEDED') unit.budgetsExceeded += 1; if (snapshotResult.status === 'NEAR_LIMIT') unit.budgetsNearLimit += 1; unit.totalBudgetedAmount = new Prisma.Decimal(unit.totalBudgetedAmount).plus(budget.amount).toString(); unit.totalSpentAmount = new Prisma.Decimal(unit.totalSpentAmount).plus(snapshotResult.spentAmount).toString(); unit.totalRemainingAmount = new Prisma.Decimal(unit.totalRemainingAmount).plus(snapshotResult.remainingAmount).toString(); result[budget.currency] = unit; } return res.json({ success: true, message: 'Admin budget summary retrieved successfully', data: result }); }
