import type { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { createGoalSchema, contributionSchema, goalHistoryQuerySchema, goalQuerySchema, updateGoalSchema, withdrawalSchema, type GoalEntryInput, type GoalInput } from '../validators/financialGoal.validator';

const goalSelect = { id: true, name: true, description: true, targetAmount: true, currentAmount: true, currency: true, startDate: true, targetDate: true, isActive: true, createdAt: true, updatedAt: true } as const;
function dateAtStart(value: string) { return new Date(`${value}T00:00:00.000Z`); }
function dateAtEnd(value: string) { return new Date(`${value}T23:59:59.999Z`); }
function validationError(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function statusFor(current: Prisma.Decimal, target: Prisma.Decimal, targetDate: Date) { if (current.greaterThanOrEqualTo(target)) return 'COMPLETED'; const progress = target.isZero() ? new Prisma.Decimal(0) : current.div(target).times(100); if (new Date() > targetDate) return 'OVERDUE'; if (progress.greaterThanOrEqualTo(80)) return 'NEAR_TARGET'; return 'ACTIVE'; }
function serialize(goal: { id: string; name: string; description: string | null; targetAmount: Prisma.Decimal; currentAmount: Prisma.Decimal; currency: 'USD' | 'SOS'; startDate: Date; targetDate: Date; isActive: boolean; createdAt: Date; updatedAt: Date }) { const remaining = goal.targetAmount.minus(goal.currentAmount); const safeRemaining = remaining.lessThan(0) ? new Prisma.Decimal(0) : remaining; const progress = goal.targetAmount.isZero() ? new Prisma.Decimal(0) : goal.currentAmount.div(goal.targetAmount).times(100); return { ...goal, targetAmount: goal.targetAmount.toString(), currentAmount: goal.currentAmount.toString(), remainingAmount: safeRemaining.toString(), progress: Number(progress.toFixed(2)), status: statusFor(goal.currentAmount, goal.targetAmount, goal.targetDate) }; }
async function getOwned(id: string, userId: string) { return getPrismaClient().financialGoal.findFirst({ where: { id, userId }, select: goalSelect }); }
async function validatePlan(input: GoalInput, currentAmount?: Prisma.Decimal, currentCurrency?: 'USD' | 'SOS') { const start = dateAtStart(input.startDate); const target = dateAtEnd(input.targetDate); if (input.currency !== 'USD' && input.currency !== 'SOS') return { error: 'Invalid currency.' } as const; if (currentAmount && currentAmount.greaterThan(0) && input.currency !== currentCurrency) return { error: 'Currency cannot change after goal activity exists.' } as const; return { start, target } as const; }

export async function createGoal(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = createGoalSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const checked = await validatePlan(parsed.data); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); const goal = await getPrismaClient().financialGoal.create({ data: { userId: req.user.id, name: parsed.data.name.trim(), description: parsed.data.description || null, targetAmount: new Prisma.Decimal(parsed.data.targetAmount), currentAmount: new Prisma.Decimal(0), currency: parsed.data.currency, startDate: checked.start, targetDate: checked.target, isActive: true }, select: goalSelect }); return res.status(201).json({ success: true, message: 'FinancialGoal goal created successfully', data: serialize(goal) }); }

export async function getGoals(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = goalQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const goals = await getPrismaClient().financialGoal.findMany({ where: { userId: req.user.id, ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }, select: goalSelect, orderBy: { createdAt: 'desc' } }); const enriched = goals.map(serialize); const filtered = filters.status ? enriched.filter((goal) => goal.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; return res.json({ success: true, message: 'FinancialGoal goals retrieved successfully', data: filtered.slice(start, start + filters.limit), pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getGoalById(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const goal = await getOwned(id, req.user.id); if (!goal) return res.status(404).json({ success: false, message: 'FinancialGoal goal not found.' }); const entries = await getPrismaClient().financialGoalEntry.findMany({ where: { goalId: id, userId: req.user.id }, orderBy: { date: 'desc' }, take: 10, select: { id: true, type: true, amount: true, description: true, date: true, createdAt: true } }); return res.json({ success: true, message: 'FinancialGoal goal retrieved successfully', data: { ...serialize(goal), recentEntries: entries.map((entry) => ({ ...entry, amount: entry.amount.toString() })) } }); }

export async function updateGoal(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const parsed = updateGoalSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const existing = await getOwned(id, req.user.id); if (!existing) return res.status(404).json({ success: false, message: 'FinancialGoal goal not found.' }); if (existing.currentAmount.greaterThan(0) && existing.currency !== parsed.data.currency) return res.status(409).json({ success: false, message: 'Currency cannot change after goal activity exists.' }); const checked = await validatePlan(parsed.data, existing.currentAmount, existing.currency); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); const goal = await getPrismaClient().financialGoal.update({ where: { id }, data: { name: parsed.data.name.trim(), description: parsed.data.description || null, targetAmount: new Prisma.Decimal(parsed.data.targetAmount), currency: parsed.data.currency, startDate: checked.start, targetDate: checked.target }, select: goalSelect }); return res.json({ success: true, message: 'FinancialGoal goal updated successfully', data: serialize(goal) }); }

export async function deactivateGoal(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const result = await getPrismaClient().financialGoal.updateMany({ where: { id, userId: req.user.id, isActive: true }, data: { isActive: false } }); if (!result.count) return res.status(404).json({ success: false, message: 'FinancialGoal goal not found.' }); return res.json({ success: true, message: 'FinancialGoal goal deactivated successfully' }); }

export async function restoreGoal(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const result = await getPrismaClient().financialGoal.updateMany({ where: { id, userId: req.user.id, isActive: false }, data: { isActive: true } }); if (!result.count) return res.status(404).json({ success: false, message: 'FinancialGoal goal not found.' }); const goal = await getOwned(id, req.user.id); return res.json({ success: true, message: 'FinancialGoal goal restored successfully', data: goal ? serialize(goal) : null }); }

async function addEntry(req: Request, res: Response, type: 'CONTRIBUTION' | 'WITHDRAWAL') { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = (type === 'CONTRIBUTION' ? contributionSchema : withdrawalSchema).safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const data: GoalEntryInput = parsed.data; try { const result = await getPrismaClient().$transaction(async (tx) => { const goal = await tx.financialGoal.findFirst({ where: { id: typeof req.params.id === 'string' ? req.params.id : req.params.id[0], userId: req.user!.id, isActive: true } }); if (!goal) throw new Error('GOAL_NOT_FOUND'); const amount = new Prisma.Decimal(data.amount); if (type === 'WITHDRAWAL' && goal.currentAmount.lessThan(amount)) throw new Error('INSUFFICIENT_GOAL'); const nextAmount = type === 'CONTRIBUTION' ? goal.currentAmount.plus(amount) : goal.currentAmount.minus(amount); const entry = await tx.financialGoalEntry.create({ data: { goalId: goal.id, userId: req.user!.id, type, amount, description: data.description || null, date: dateAtStart(data.date) } }); const updated = await tx.financialGoal.update({ where: { id: goal.id }, data: { currentAmount: nextAmount }, select: goalSelect }); return { updated, entry }; }); return res.status(201).json({ success: true, message: type === 'CONTRIBUTION' ? 'Goal contribution added successfully' : 'FinancialGoal withdrawal completed successfully', data: { ...serialize(result.updated), entry: { ...result.entry, amount: result.entry.amount.toString() } } }); } catch (error) { if (error instanceof Error && error.message === 'GOAL_NOT_FOUND') return res.status(404).json({ success: false, message: 'FinancialGoal goal not found or inactive.' }); if (error instanceof Error && error.message === 'INSUFFICIENT_GOAL') return res.status(409).json({ success: false, message: 'Insufficient goal balance.' }); throw error; } }
export async function contributeToGoal(req: Request, res: Response) { return addEntry(req, res, 'CONTRIBUTION'); }
export async function withdrawFromGoal(req: Request, res: Response) { return addEntry(req, res, 'WITHDRAWAL'); }

export async function getGoalHistory(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; if (!(await getOwned(id, req.user.id))) return res.status(404).json({ success: false, message: 'FinancialGoal goal not found.' }); const parsed = goalHistoryQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const [entries, total] = await getPrismaClient().$transaction([getPrismaClient().financialGoalEntry.findMany({ where: { goalId: id, userId: req.user.id }, orderBy: { date: 'desc' }, skip: (parsed.data.page - 1) * parsed.data.limit, take: parsed.data.limit, select: { id: true, type: true, amount: true, description: true, date: true, createdAt: true } }), getPrismaClient().financialGoalEntry.count({ where: { goalId: id, userId: req.user.id } })]); return res.json({ success: true, message: 'FinancialGoal history retrieved successfully', data: entries.map((entry) => ({ ...entry, amount: entry.amount.toString() })), pagination: { page: parsed.data.page, limit: parsed.data.limit, total, totalPages: Math.ceil(total / parsed.data.limit) } }); }

export async function getGoalSummary(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = goalQuerySchema.pick({ currency: true }).safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const goals = await getPrismaClient().financialGoal.findMany({ where: { userId: req.user.id, ...(parsed.data.currency ? { currency: parsed.data.currency } : {}) }, select: { targetAmount: true, currentAmount: true, currency: true, isActive: true, targetDate: true } }); const result: Record<string, { targetAmount: string; savedAmount: string; remainingAmount: string; totalGoals: number; activeGoals: number; completedGoals: number; overdueGoals: number }> = {}; for (const goal of goals) { const unit = result[goal.currency] ?? { targetAmount: '0', savedAmount: '0', remainingAmount: '0', totalGoals: 0, activeGoals: 0, completedGoals: 0, overdueGoals: 0 }; const status = statusFor(goal.currentAmount, goal.targetAmount, goal.targetDate); const remaining = goal.targetAmount.minus(goal.currentAmount); unit.targetAmount = new Prisma.Decimal(unit.targetAmount).plus(goal.targetAmount).toString(); unit.savedAmount = new Prisma.Decimal(unit.savedAmount).plus(goal.currentAmount).toString(); unit.remainingAmount = new Prisma.Decimal(unit.remainingAmount).plus(remaining.greaterThan(0) ? remaining : new Prisma.Decimal(0)).toString(); unit.totalGoals += 1; if (goal.isActive) unit.activeGoals += 1; if (status === 'COMPLETED') unit.completedGoals += 1; if (status === 'OVERDUE') unit.overdueGoals += 1; result[goal.currency] = unit; } return res.json({ success: true, message: 'FinancialGoal summary retrieved successfully', data: result }); }

export async function listAdminGoals(req: Request, res: Response) { const parsed = goalQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const goals = await getPrismaClient().financialGoal.findMany({ where: { ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }, select: { ...goalSelect, user: { select: { id: true, name: true, email: true } } }, orderBy: { createdAt: 'desc' } }); const enriched = goals.map(serialize); const filtered = filters.status ? enriched.filter((goal) => goal.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; return res.json({ success: true, message: 'Admin goal retrieved successfully', data: filtered.slice(start, start + filters.limit), pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getAdminGoalSummary(req: Request, res: Response) { const goals = await getPrismaClient().financialGoal.findMany({ select: { targetAmount: true, currentAmount: true, currency: true, isActive: true, targetDate: true } }); const result: Record<string, { targetAmount: string; savedAmount: string; remainingAmount: string; totalGoals: number; activeGoals: number; completedGoals: number; overdueGoals: number }> = {}; for (const goal of goals) { const unit = result[goal.currency] ?? { targetAmount: '0', savedAmount: '0', remainingAmount: '0', totalGoals: 0, activeGoals: 0, completedGoals: 0, overdueGoals: 0 }; const status = statusFor(goal.currentAmount, goal.targetAmount, goal.targetDate); const remaining = goal.targetAmount.minus(goal.currentAmount); unit.targetAmount = new Prisma.Decimal(unit.targetAmount).plus(goal.targetAmount).toString(); unit.savedAmount = new Prisma.Decimal(unit.savedAmount).plus(goal.currentAmount).toString(); unit.remainingAmount = new Prisma.Decimal(unit.remainingAmount).plus(remaining.greaterThan(0) ? remaining : new Prisma.Decimal(0)).toString(); unit.totalGoals += 1; if (goal.isActive) unit.activeGoals += 1; if (status === 'COMPLETED') unit.completedGoals += 1; if (status === 'OVERDUE') unit.overdueGoals += 1; result[goal.currency] = unit; } return res.json({ success: true, message: 'Admin goal summary retrieved successfully', data: result }); }
