import { Request, Response } from 'express';
import { getPrismaClient } from '../config/prisma';
import { processNotificationReminders } from '../services/notificationReminder.service';
import { createNotification } from '../utils/notification.utils';
import { deviceRegistrationSchema, notificationPreferenceUpdateSchema, notificationQuerySchema, reminderProcessSchema } from '../validators/notification.validator';

const types = ['BUDGET_ALERT', 'SAVINGS_REMINDER', 'GOAL_REMINDER', 'BUDGET_WARNING', 'BUDGET_EXCEEDED', 'SAVINGS_PROGRESS', 'SAVINGS_COMPLETED', 'GOAL_PROGRESS', 'GOAL_DEADLINE', 'GOAL_COMPLETED', 'RECURRING_UPCOMING', 'RECURRING_GENERATED', 'SYSTEM'] as const;
function validationError(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function idOf(req: Request) { return typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; }
function serialize(notification: { id: string; type: string; title: string; message: string; entityType: string | null; entityId: string | null; isRead: boolean; createdAt: Date; updatedAt: Date }) { return notification; }

export async function getNotifications(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); await processNotificationReminders(req.user.id); const parsed = notificationQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const where = { userId: req.user.id, ...(typeof filters.isRead === 'boolean' ? { isRead: filters.isRead } : {}), ...(filters.type ? { type: filters.type } : {}) }; const prisma = getPrismaClient(); const [rows, total] = await prisma.$transaction([prisma.notification.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (filters.page - 1) * filters.limit, take: filters.limit, select: { id: true, type: true, title: true, message: true, entityType: true, entityId: true, isRead: true, createdAt: true, updatedAt: true } }), prisma.notification.count({ where })]); return res.json({ success: true, message: 'Notifications retrieved successfully', data: rows.map(serialize), pagination: { page: filters.page, limit: filters.limit, total, totalPages: Math.ceil(total / filters.limit) } }); }
export async function getNotificationById(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const notification = await getPrismaClient().notification.findFirst({ where: { id: idOf(req), userId: req.user.id }, select: { id: true, type: true, title: true, message: true, entityType: true, entityId: true, isRead: true, createdAt: true, updatedAt: true } }); if (!notification) return res.status(404).json({ success: false, message: 'Notification not found.' }); return res.json({ success: true, message: 'Notification retrieved successfully', data: notification }); }
export async function markAsRead(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const updated = await getPrismaClient().notification.updateMany({ where: { id: idOf(req), userId: req.user.id, isRead: false }, data: { isRead: true } }); if (!updated.count) return res.status(404).json({ success: false, message: 'Notification not found or already read.' }); return res.json({ success: true, message: 'Notification marked as read.' }); }
export async function markAllAsRead(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const updated = await getPrismaClient().notification.updateMany({ where: { userId: req.user.id, isRead: false }, data: { isRead: true } }); return res.json({ success: true, message: 'Notifications marked as read.', data: { updated: updated.count } }); }
export async function deleteNotification(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const deleted = await getPrismaClient().notification.deleteMany({ where: { id: idOf(req), userId: req.user.id } }); if (!deleted.count) return res.status(404).json({ success: false, message: 'Notification not found.' }); return res.json({ success: true, message: 'Notification deleted.' }); }
export async function clearNotifications(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const deleted = await getPrismaClient().notification.deleteMany({ where: { userId: req.user.id } }); return res.json({ success: true, message: 'Notifications cleared.', data: { deleted: deleted.count } }); }
export async function getUnreadCount(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const count = await getPrismaClient().notification.count({ where: { userId: req.user.id, isRead: false } }); return res.json({ success: true, message: 'Unread count retrieved successfully.', data: { count } }); }
export async function getNotificationPreferences(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const preferences = await getPrismaClient().notificationPreference.upsert({ where: { userId: req.user.id }, create: { userId: req.user.id }, update: {}, select: { id: true, budgetNotifications: true, savingsNotifications: true, goalNotifications: true, recurringNotifications: true, systemNotifications: true, pushEnabled: true, createdAt: true, updatedAt: true } }); return res.json({ success: true, message: 'Notification preferences retrieved successfully.', data: preferences }); }
export async function updateNotificationPreferences(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = notificationPreferenceUpdateSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const preferences = await getPrismaClient().notificationPreference.upsert({ where: { userId: req.user.id }, create: { userId: req.user.id, ...parsed.data }, update: parsed.data, select: { id: true, budgetNotifications: true, savingsNotifications: true, goalNotifications: true, recurringNotifications: true, systemNotifications: true, pushEnabled: true, createdAt: true, updatedAt: true } }); return res.json({ success: true, message: 'Notification preferences updated successfully.', data: preferences }); }
export async function registerDevice(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = deviceRegistrationSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const device = await getPrismaClient().userDevice.upsert({ where: { expoPushToken: parsed.data.expoPushToken }, create: { userId: req.user.id, expoPushToken: parsed.data.expoPushToken, platform: parsed.data.platform, isActive: true, lastRegisteredAt: new Date() }, update: { userId: req.user.id, platform: parsed.data.platform, isActive: true, lastRegisteredAt: new Date() }, select: { id: true, expoPushToken: true, platform: true, isActive: true, lastRegisteredAt: true } }); return res.status(201).json({ success: true, message: 'Push device registered successfully.', data: device }); }
export async function unregisterDevice(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const result = await getPrismaClient().userDevice.updateMany({ where: { id: idOf(req), userId: req.user.id }, data: { isActive: false } }); if (!result.count) return res.status(404).json({ success: false, message: 'Device not found.' }); return res.json({ success: true, message: 'Push device disabled.' }); }
export async function processReminders(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = reminderProcessSchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const asOf = parsed.data.asOf ? new Date(`${parsed.data.asOf}T12:00:00.000Z`) : new Date(); const result = await processNotificationReminders(req.user.id, asOf); return res.json({ success: true, message: 'Notification reminders processed successfully.', data: result }); }
export async function createSystemNotification(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = req.body as { title?: unknown; message?: unknown; eventKey?: unknown }; if (typeof parsed.title !== 'string' || typeof parsed.message !== 'string') return res.status(400).json({ success: false, message: 'Title and message are required.' }); const notification = await createNotification({ userId: req.user.id, type: 'SYSTEM', title: parsed.title.trim(), message: parsed.message.trim(), entityType: 'SYSTEM', eventKey: typeof parsed.eventKey === 'string' ? parsed.eventKey : null }); return res.status(201).json({ success: true, message: notification ? 'System notification created.' : 'System notification skipped by preferences or idempotency.', data: notification }); }

export async function listAdminNotifications(req: Request, res: Response) { const parsed = (await import('../validators/notification.validator')).adminNotificationQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const where = { ...(typeof filters.isRead === 'boolean' ? { isRead: filters.isRead } : {}), ...(filters.type ? { type: filters.type } : {}), ...(filters.search ? { OR: [{ title: { contains: filters.search, mode: 'insensitive' as const } }, { message: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }; const prisma = getPrismaClient(); const [rows, total] = await prisma.$transaction([prisma.notification.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (filters.page - 1) * filters.limit, take: filters.limit, select: { id: true, type: true, title: true, message: true, entityType: true, entityId: true, isRead: true, createdAt: true, user: { select: { id: true, name: true, email: true } } } }), prisma.notification.count({ where })]); return res.json({ success: true, message: 'Admin notifications retrieved successfully.', data: rows, pagination: { page: filters.page, limit: filters.limit, total, totalPages: Math.ceil(total / filters.limit) } }); }
export async function getAdminNotificationSummary(_req: Request, res: Response) { const prisma = getPrismaClient(); const [byType, unread, total, preferences] = await Promise.all([prisma.notification.groupBy({ by: ['type'], _count: { _all: true } }), prisma.notification.count({ where: { isRead: false } }), prisma.notification.count(), prisma.notificationPreference.count({ where: { pushEnabled: true } })]); return res.json({ success: true, message: 'Admin notification summary retrieved successfully.', data: { total, unread, pushEnabledUsers: preferences, byType: Object.fromEntries(byType.map((row) => [row.type, row._count._all])) } }); }
