import { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { processRecurringTransactions, addInterval, dateAtStart, dateKey, serializeRecurring } from '../services/recurringTransaction.service';
import { createRecurringTransactionSchema, processQuerySchema, recurringTransactionQuerySchema, upcomingQuerySchema, updateRecurringTransactionSchema, type RecurringTransactionInput } from '../validators/recurringTransaction.validator';

const categorySelect = { id: true, name: true, type: true, icon: true } as const;
const recurringSelect = { id: true, type: true, categoryId: true, name: true, description: true, amount: true, currency: true, frequency: true, interval: true, startDate: true, endDate: true, nextRunDate: true, lastRunDate: true, isActive: true, isPaused: true, createdAt: true, updatedAt: true, category: { select: categorySelect }, _count: { select: { transactions: true } } } as const;
function validationError(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function idOf(req: Request) { return typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; }
async function accessibleCategory(userId: string, categoryId: string, type: 'INCOME' | 'EXPENSE') { return getPrismaClient().category.findFirst({ where: { id: categoryId, type: type === 'INCOME' ? 'INCOME' : 'EXPENSE', isActive: true, OR: [{ isDefault: true }, { userId }] }, select: { id: true, type: true } }); }
function nextFromInput(input: { startDate: string; frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'; interval: number }, lastRunDate?: Date | null) { return lastRunDate ? addInterval(lastRunDate, input.frequency, input.interval) : dateAtStart(input.startDate); }
function serialize(schedule: any) { return serializeRecurring(schedule); }

export async function createRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = createRecurringTransactionSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const data = parsed.data; const category = await accessibleCategory(req.user.id, data.categoryId, data.type); if (!category) return res.status(400).json({ success: false, message: 'Category is not available, inactive, or does not match the transaction type.' }); const schedule = await getPrismaClient().recurringTransaction.create({ data: { userId: req.user.id, type: data.type, categoryId: data.categoryId, name: data.name, description: data.description || null, amount: new Prisma.Decimal(data.amount), currency: data.currency, frequency: data.frequency, interval: data.interval, startDate: dateAtStart(data.startDate), endDate: data.endDate ? dateAtStart(data.endDate) : null, nextRunDate: dateAtStart(data.startDate) }, select: recurringSelect }); return res.status(201).json({ success: true, message: 'Recurring transaction created successfully', data: serialize(schedule) }); }

export async function listRecurringTransactions(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = recurringTransactionQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const where = { userId: req.user.id, ...(filters.type ? { type: filters.type } : {}), ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(typeof filters.isPaused === 'boolean' ? { isPaused: filters.isPaused } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }; const prisma = getPrismaClient(); const [rows, total] = await prisma.$transaction([prisma.recurringTransaction.findMany({ where, select: recurringSelect, orderBy: { nextRunDate: 'asc' }, skip: (filters.page - 1) * filters.limit, take: filters.limit }), prisma.recurringTransaction.count({ where })]); return res.json({ success: true, message: 'Recurring transactions retrieved successfully', data: rows.map(serialize), pagination: { page: filters.page, limit: filters.limit, total, totalPages: Math.ceil(total / filters.limit) } }); }

export async function getRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const schedule = await getPrismaClient().recurringTransaction.findFirst({ where: { id: idOf(req), userId: req.user.id }, select: recurringSelect }); if (!schedule) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); return res.json({ success: true, message: 'Recurring transaction retrieved successfully', data: serialize(schedule) }); }

export async function updateRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = idOf(req); const parsed = updateRecurringTransactionSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const prisma = getPrismaClient(); const existing = await prisma.recurringTransaction.findFirst({ where: { id, userId: req.user.id } }); if (!existing) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); const data = parsed.data; const type = data.type ?? existing.type; const categoryId = data.categoryId ?? existing.categoryId; const category = await accessibleCategory(req.user.id, categoryId, type); if (!category) return res.status(400).json({ success: false, message: 'Category is not available, inactive, or does not match the transaction type.' }); const startDate = data.startDate ?? dateKey(existing.startDate); const frequency = data.frequency ?? existing.frequency; const interval = data.interval ?? existing.interval; const updated = await prisma.recurringTransaction.update({ where: { id }, data: { ...(data.name !== undefined ? { name: data.name } : {}), ...(data.description !== undefined ? { description: data.description || null } : {}), type, categoryId, ...(data.amount !== undefined ? { amount: new Prisma.Decimal(data.amount) } : {}), ...(data.currency !== undefined ? { currency: data.currency } : {}), frequency, interval, startDate: dateAtStart(startDate), ...(data.endDate !== undefined ? { endDate: data.endDate ? dateAtStart(data.endDate) : null } : {}), nextRunDate: nextFromInput({ startDate, frequency, interval }, existing.lastRunDate), isActive: existing.isActive, isPaused: existing.isPaused }, select: recurringSelect }); return res.json({ success: true, message: 'Recurring transaction updated successfully', data: serialize(updated) }); }

export async function deactivateRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const result = await getPrismaClient().recurringTransaction.updateMany({ where: { id: idOf(req), userId: req.user.id, isActive: true }, data: { isActive: false, isPaused: false } }); if (!result.count) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); return res.json({ success: true, message: 'Recurring transaction deactivated successfully' }); }
export async function restoreRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const schedule = await getPrismaClient().recurringTransaction.findFirst({ where: { id: idOf(req), userId: req.user.id } }); if (!schedule) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); const nextRunDate = schedule.lastRunDate ? addInterval(schedule.lastRunDate, schedule.frequency, schedule.interval) : schedule.startDate; const restored = await getPrismaClient().recurringTransaction.update({ where: { id: schedule.id }, data: { isActive: true, isPaused: false, nextRunDate }, select: recurringSelect }); return res.json({ success: true, message: 'Recurring transaction restored successfully', data: serialize(restored) }); }
export async function pauseRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const result = await getPrismaClient().recurringTransaction.updateMany({ where: { id: idOf(req), userId: req.user.id, isActive: true }, data: { isPaused: true } }); if (!result.count) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); return res.json({ success: true, message: 'Recurring transaction paused successfully' }); }
export async function resumeRecurringTransaction(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const schedule = await getPrismaClient().recurringTransaction.findFirst({ where: { id: idOf(req), userId: req.user.id } }); if (!schedule) return res.status(404).json({ success: false, message: 'Recurring transaction not found.' }); const nextRunDate = schedule.lastRunDate ? addInterval(schedule.lastRunDate, schedule.frequency, schedule.interval) : schedule.nextRunDate; const resumed = await getPrismaClient().recurringTransaction.update({ where: { id: schedule.id }, data: { isActive: true, isPaused: false, nextRunDate }, select: recurringSelect }); return res.json({ success: true, message: 'Recurring transaction resumed successfully', data: serialize(resumed) }); }

export async function getUpcomingOccurrences(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = upcomingQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const now = new Date(); const until = new Date(now.getTime() + parsed.data.days * 86400000); const schedules = await getPrismaClient().recurringTransaction.findMany({ where: { userId: req.user.id, isActive: true, isPaused: false }, select: recurringSelect, orderBy: { nextRunDate: 'asc' } }); const occurrences: Array<{ recurringTransactionId: string; name: string; type: string; amount: string; currency: string; category: unknown; occurrenceDate: string }> = []; for (const schedule of schedules) { let occurrence = schedule.nextRunDate; let count = 0; while (occurrence <= until && count < 100) { if (occurrence >= now && (!schedule.endDate || occurrence <= schedule.endDate)) occurrences.push({ recurringTransactionId: schedule.id, name: schedule.name, type: schedule.type, amount: schedule.amount.toString(), currency: schedule.currency, category: schedule.category, occurrenceDate: occurrence.toISOString() }); occurrence = addInterval(occurrence, schedule.frequency, schedule.interval); count += 1; } } return res.json({ success: true, message: 'Upcoming recurring occurrences retrieved successfully', data: occurrences.sort((a, b) => a.occurrenceDate.localeCompare(b.occurrenceDate)) }); }

export async function processDueRecurringTransactions(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = processQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const result = await processRecurringTransactions(req.user.id, parsed.data.asOf ? dateAtStart(parsed.data.asOf) : new Date()); return res.json({ success: true, message: 'Due recurring transactions processed successfully', data: result }); }

export async function listAdminRecurringTransactions(req: Request, res: Response) { const parsed = recurringTransactionQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const where = { ...(filters.type ? { type: filters.type } : {}), ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(typeof filters.isPaused === 'boolean' ? { isPaused: filters.isPaused } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }; const prisma = getPrismaClient(); const select = { ...recurringSelect, user: { select: { id: true, name: true, email: true } } } as const; const [rows, total] = await prisma.$transaction([prisma.recurringTransaction.findMany({ where, select, orderBy: { nextRunDate: 'asc' }, skip: (filters.page - 1) * filters.limit, take: filters.limit }), prisma.recurringTransaction.count({ where })]); return res.json({ success: true, message: 'Admin recurring transactions retrieved successfully', data: rows.map(serialize), pagination: { page: filters.page, limit: filters.limit, total, totalPages: Math.ceil(total / filters.limit) } }); }
export async function getAdminRecurringSummary(_req: Request, res: Response) { const rows = await getPrismaClient().recurringTransaction.findMany({ select: { amount: true, currency: true, isActive: true, isPaused: true, _count: { select: { transactions: true } } } }); const result: Record<string, { total: number; active: number; paused: number; inactive: number; generated: number; scheduledAmount: string }> = {}; for (const row of rows) { const summary = result[row.currency] ?? { total: 0, active: 0, paused: 0, inactive: 0, generated: 0, scheduledAmount: '0' }; summary.total += 1; if (!row.isActive) summary.inactive += 1; else if (row.isPaused) summary.paused += 1; else summary.active += 1; summary.generated += row._count.transactions; summary.scheduledAmount = new Prisma.Decimal(summary.scheduledAmount).plus(row.amount).toString(); result[row.currency] = summary; } return res.json({ success: true, message: 'Admin recurring summary retrieved successfully', data: result }); }
