import { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { reportQuerySchema } from '../validators/report.validator';
import { budgetReport, categoryRows, currencies, goalsReport, overviewRows, recurringReport, resolvePeriod, savingsReport, spendingAnalysis, transactions, trendRows } from '../services/report.service';
function validationError(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
async function query(req: Request, res: Response) { if (!req.user) { res.status(401).json({ success: false, message: 'Authentication is required.' }); return null; } const parsed = reportQuerySchema.safeParse(req.query); if (!parsed.success) { validationError(res, parsed.error); return null; } return { userId: req.user.id, query: parsed.data, period: resolvePeriod(parsed.data) }; }
function trendPeriod(period: ReturnType<typeof resolvePeriod>, months: number, custom = false) { if (custom || months <= 1) return period; const s = new Date(Date.UTC(period.end.getUTCFullYear(), period.end.getUTCMonth() - months + 1, 1)); return { ...period, start: s }; }
function change(current: string, previous: string) { const c = new Prisma.Decimal(current); const p = new Prisma.Decimal(previous); return { amount: c.minus(p).toString(), percentage: p.isZero() ? null : Number(c.minus(p).div(p).times(100).toFixed(2)) }; }
export async function overview(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const data = overviewRows(rows); return res.json({ success: true, message: 'Overview report retrieved successfully.', data }); }
export async function income(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const byCurrency: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) { const selected = rows.filter((r) => r.currency === c && r.type === 'INCOME'); const total = selected.reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)); byCurrency[c] = { totalIncome: total.toString(), incomeByCategory: categoryRows(selected)[c] ?? [], incomeByMonth: trendRows(selected, ctx.period, 'month'), topIncomeCategories: categoryRows(selected)[c]?.slice(0, 5) ?? [] }; } return res.json({ success: true, message: 'Income report retrieved successfully.', data: byCurrency }); }
export async function expenses(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const byCurrency: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) { const selected = rows.filter((r) => r.currency === c && r.type === 'EXPENSE'); const total = selected.reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)); byCurrency[c] = { totalExpenses: total.toString(), expenseByCategory: categoryRows(selected)[c] ?? [], expenseByMonth: trendRows(selected, ctx.period, 'month'), topExpenseCategories: categoryRows(selected)[c]?.slice(0, 5) ?? [] }; } return res.json({ success: true, message: 'Expense report retrieved successfully.', data: byCurrency }); }
export async function categories(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); return res.json({ success: true, message: 'Category report retrieved successfully.', data: categoryRows(rows) }); }
export async function monthlyTrend(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const p = trendPeriod(ctx.period, ctx.query.months, ctx.query.period === 'CUSTOM'); const rows = await transactions(ctx.userId, p, ctx.query.currency); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) data[c] = trendRows(rows.filter((r) => r.currency === c), p, 'month'); return res.json({ success: true, message: 'Monthly trend retrieved successfully.', data }); }
export async function dailyTrend(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) data[c] = trendRows(rows.filter((r) => r.currency === c), ctx.period, 'day'); return res.json({ success: true, message: 'Daily trend retrieved successfully.', data }); }
export async function budgets(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await budgetReport(ctx.userId, ctx.period, ctx.query.currency); const data: Record<string, any[]> = {}; for (const c of currencies(ctx.query.currency)) data[c] = rows.filter((r) => r.currency === c); return res.json({ success: true, message: 'Budget report retrieved successfully.', data }); }
export async function savings(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; return res.json({ success: true, message: 'Savings report retrieved successfully.', data: await savingsReport(ctx.userId, ctx.period, ctx.query.currency) }); }
export async function goals(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; return res.json({ success: true, message: 'Goals report retrieved successfully.', data: await goalsReport(ctx.userId, ctx.query.currency) }); }
export async function recurring(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; return res.json({ success: true, message: 'Recurring report retrieved successfully.', data: await recurringReport(ctx.userId, ctx.period, ctx.query.currency) }); }
export async function spending(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) data[c] = spendingAnalysis(rows.filter((r) => r.currency === c), ctx.period); return res.json({ success: true, message: 'Spending analysis retrieved successfully.', data }); }
export async function incomeVsExpense(req: Request, res: Response) { return monthlyTrend(req, res); }
export async function comparison(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const current = overviewRows(await transactions(ctx.userId, ctx.period, ctx.query.currency)); const previous = overviewRows(await transactions(ctx.userId, { start: ctx.period.previousStart, end: ctx.period.previousEnd, previousStart: ctx.period.previousStart, previousEnd: ctx.period.previousEnd }, ctx.query.currency)); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) data[c] = { currentPeriod: current[c], previousPeriod: previous[c], incomeChange: change(current[c].totalIncome, previous[c].totalIncome), expenseChange: change(current[c].totalExpenses, previous[c].totalExpenses), netChange: change(current[c].netBalance, previous[c].netBalance) }; return res.json({ success: true, message: 'Comparison report retrieved successfully.', data }); }
export async function financialHealth(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await transactions(ctx.userId, ctx.period, ctx.query.currency); const overviewData = overviewRows(rows); const savingsData = await savingsReport(ctx.userId, ctx.period, ctx.query.currency); const budgetData = await budgetReport(ctx.userId, ctx.period, ctx.query.currency); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) { const o = overviewData[c]; const income = new Prisma.Decimal(o.totalIncome); const expense = new Prisma.Decimal(o.totalExpenses); const saved = new Prisma.Decimal(savingsData[c]?.savingsProgress ?? 0); const budgetRows = budgetData.filter((b) => b.currency === c); const limit = budgetRows.reduce((s, b) => s.plus(b.limit), new Prisma.Decimal(0)); const spent = budgetRows.reduce((s, b) => s.plus(b.spent), new Prisma.Decimal(0)); const savingsRate = income.isZero() ? 0 : Number(saved.div(income).times(100).toFixed(2)); const expenseRate = income.isZero() ? 0 : Number(expense.div(income).times(100).toFixed(2)); const budgetUsage = limit.isZero() ? 0 : Number(spent.div(limit).times(100).toFixed(2)); const monthsWithIncome = new Set(rows.filter((r) => r.currency === c && r.type === 'INCOME').map((r) => r.date.toISOString().slice(0, 7))).size; const periodMonths = Math.max(1, Math.ceil((ctx.period.end.getTime() - ctx.period.start.getTime()) / (86400000 * 30.4375))); const incomeStability = Number(Math.min(100, monthsWithIncome / periodMonths * 100).toFixed(2)); const factors = { savingsRate, expenseRate, budgetUsage, incomeStability }; const score = Number(((Math.min(100, savingsRate) + Math.max(0, 100 - Math.min(100, budgetUsage)) + incomeStability + Math.max(0, 100 - Math.min(100, expenseRate))) / 4).toFixed(2)); data[c] = { ...factors, financialHealthScore: score, financialBalance: o.netBalance, methodology: 'Equal-weight average of savings rate, budget discipline, income stability, and inverse expense rate.' }; } return res.json({ success: true, message: 'Financial health report retrieved successfully.', data }); }

export async function adminOverview(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const rows = await getPrismaClient().transaction.findMany({ where: { isDeleted: false, ...(ctx.query.currency ? { currency: ctx.query.currency } : {}), date: { gte: ctx.period.start, lte: ctx.period.end } }, select: { amount: true, type: true, currency: true } }); const data: Record<string, any> = {}; for (const c of currencies(ctx.query.currency)) { const selected = rows.filter((r) => r.currency === c); const income = selected.filter((r) => r.type === 'INCOME').reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)); const expense = selected.filter((r) => r.type === 'EXPENSE').reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)); data[c] = { totalIncome: income.toString(), totalExpenses: expense.toString(), netBalance: income.minus(expense).toString(), transactionCount: selected.length }; } return res.json({ success: true, message: 'Admin financial overview retrieved successfully.', data }); }

export async function debts(req: Request, res: Response) { const ctx = await query(req, res); if (!ctx) return; const prisma = getPrismaClient(); const rows = await prisma.debt.findMany({ where: { userId: ctx.userId, isDeleted: false }, select: { type: true, status: true, currency: true, originalAmount: true, remainingAmount: true, _count: { select: { repayments: true } } } }); const repayments = await prisma.debtRepayment.findMany({ where: { userId: ctx.userId, paymentDate: { gte: ctx.period.start, lte: ctx.period.end } }, select: { amount: true, currency: true, debt: { select: { type: true } } } }); const data: Record<string, any> = {}; for (const currency of currencies(ctx.query.currency)) { const selected = rows.filter((r) => r.currency === currency); const paidRows = repayments.filter((r) => r.currency === currency); const iOwe = selected.filter((r) => r.type === 'I_OWE'); const owedToMe = selected.filter((r) => r.type === 'OWED_TO_ME'); data[currency] = { totalIOwe: iOwe.reduce((s, r) => s.plus(r.remainingAmount), new Prisma.Decimal(0)).toString(), totalOwedToMe: owedToMe.reduce((s, r) => s.plus(r.remainingAmount), new Prisma.Decimal(0)).toString(), totalOriginal: selected.reduce((s, r) => s.plus(r.originalAmount), new Prisma.Decimal(0)).toString(), totalPaid: selected.reduce((s, r) => s.plus(r.originalAmount.minus(r.remainingAmount)), new Prisma.Decimal(0)).toString(), totalRemaining: selected.reduce((s, r) => s.plus(r.remainingAmount), new Prisma.Decimal(0)).toString(), activeDebts: selected.filter((r) => ['ACTIVE', 'PARTIALLY_PAID'].includes(r.status)).length, overdueDebts: selected.filter((r) => r.status === 'OVERDUE').length, paidDebts: selected.filter((r) => r.status === 'PAID').length, cashflow: { paidTowardDebts: paidRows.filter((r) => r.debt.type === 'I_OWE').reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)).toString(), receivedFromDebtors: paidRows.filter((r) => r.debt.type === 'OWED_TO_ME').reduce((s, r) => s.plus(r.amount), new Prisma.Decimal(0)).toString() } }; } return res.json({ success: true, message: 'Debt report retrieved successfully.', data }); }
