import type { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';
import { createSavingsSchema, depositSavingsSchema, savingsHistoryQuerySchema, savingsQuerySchema, updateSavingsSchema, withdrawSavingsSchema, type SavingsEntryInput, type SavingsInput } from '../validators/savings.validator';

const savingsSelect = { id: true, name: true, description: true, targetAmount: true, currentAmount: true, currency: true, startDate: true, targetDate: true, isActive: true, createdAt: true, updatedAt: true } as const;
function dateAtStart(value: string) { return new Date(`${value}T00:00:00.000Z`); }
function dateAtEnd(value: string) { return new Date(`${value}T23:59:59.999Z`); }
function validationError(res: Response, error: { issues: Array<{ path: (string | number)[]; message: string }> }) { return res.status(400).json({ success: false, message: 'Validation failed.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })) }); }
function statusFor(current: Prisma.Decimal, target: Prisma.Decimal, targetDate: Date) { if (current.greaterThanOrEqualTo(target)) return 'COMPLETED'; const progress = target.isZero() ? new Prisma.Decimal(0) : current.div(target).times(100); if (new Date() > targetDate) return 'OVERDUE'; if (progress.greaterThanOrEqualTo(80)) return 'NEAR_TARGET'; return 'ACTIVE'; }
function serialize(plan: { id: string; name: string; description: string | null; targetAmount: Prisma.Decimal; currentAmount: Prisma.Decimal; currency: 'USD' | 'SOS'; startDate: Date; targetDate: Date; isActive: boolean; createdAt: Date; updatedAt: Date }) { const remaining = plan.targetAmount.minus(plan.currentAmount); const safeRemaining = remaining.lessThan(0) ? new Prisma.Decimal(0) : remaining; const progress = plan.targetAmount.isZero() ? new Prisma.Decimal(0) : plan.currentAmount.div(plan.targetAmount).times(100); return { ...plan, targetAmount: plan.targetAmount.toString(), currentAmount: plan.currentAmount.toString(), remainingAmount: safeRemaining.toString(), progress: Number(progress.toFixed(2)), status: statusFor(plan.currentAmount, plan.targetAmount, plan.targetDate) }; }
async function getOwned(id: string, userId: string) { return getPrismaClient().savings.findFirst({ where: { id, userId }, select: savingsSelect }); }
async function validatePlan(userId: string, input: SavingsInput, currentAmount?: Prisma.Decimal) { const start = dateAtStart(input.startDate); const target = dateAtEnd(input.targetDate); if (input.currency !== 'USD' && input.currency !== 'SOS') return { error: 'Invalid currency.' } as const; if (currentAmount && currentAmount.greaterThan(0) && input.currency !== (await getPrismaClient().savings.findFirst({ where: { userId }, select: { currency: true } }))?.currency) return { error: 'Currency cannot change after savings activity exists.' } as const; return { start, target } as const; }

export async function createSavings(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = createSavingsSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const checked = await validatePlan(req.user.id, parsed.data); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); const plan = await getPrismaClient().savings.create({ data: { userId: req.user.id, name: parsed.data.name.trim(), description: parsed.data.description || null, targetAmount: new Prisma.Decimal(parsed.data.targetAmount), currentAmount: new Prisma.Decimal(0), currency: parsed.data.currency, startDate: checked.start, targetDate: checked.target, isActive: true }, select: savingsSelect }); return res.status(201).json({ success: true, message: 'Savings plan created successfully', data: serialize(plan) }); }

export async function getSavings(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = savingsQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const plans = await getPrismaClient().savings.findMany({ where: { userId: req.user.id, ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }, select: savingsSelect, orderBy: { createdAt: 'desc' } }); const enriched = plans.map(serialize); const filtered = filters.status ? enriched.filter((plan) => plan.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; return res.json({ success: true, message: 'Savings plans retrieved successfully', data: filtered.slice(start, start + filters.limit), pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getSavingsById(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const plan = await getOwned(id, req.user.id); if (!plan) return res.status(404).json({ success: false, message: 'Savings plan not found.' }); const entries = await getPrismaClient().savingsEntry.findMany({ where: { savingsId: id, userId: req.user.id }, orderBy: { date: 'desc' }, take: 10, select: { id: true, type: true, amount: true, description: true, date: true, createdAt: true } }); return res.json({ success: true, message: 'Savings plan retrieved successfully', data: { ...serialize(plan), recentEntries: entries.map((entry) => ({ ...entry, amount: entry.amount.toString() })) } }); }

export async function updateSavings(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const parsed = updateSavingsSchema.safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const existing = await getOwned(id, req.user.id); if (!existing) return res.status(404).json({ success: false, message: 'Savings plan not found.' }); if (existing.currentAmount.greaterThan(0) && existing.currency !== parsed.data.currency) return res.status(409).json({ success: false, message: 'Currency cannot change after savings activity exists.' }); const checked = await validatePlan(req.user.id, parsed.data, existing.currentAmount); if ('error' in checked) return res.status(400).json({ success: false, message: checked.error }); const plan = await getPrismaClient().savings.update({ where: { id }, data: { name: parsed.data.name.trim(), description: parsed.data.description || null, targetAmount: new Prisma.Decimal(parsed.data.targetAmount), currency: parsed.data.currency, startDate: checked.start, targetDate: checked.target }, select: savingsSelect }); return res.json({ success: true, message: 'Savings plan updated successfully', data: serialize(plan) }); }

export async function deactivateSavings(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const result = await getPrismaClient().savings.updateMany({ where: { id, userId: req.user.id, isActive: true }, data: { isActive: false } }); if (!result.count) return res.status(404).json({ success: false, message: 'Savings plan not found.' }); return res.json({ success: true, message: 'Savings plan deactivated successfully' }); }

export async function restoreSavings(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; const result = await getPrismaClient().savings.updateMany({ where: { id, userId: req.user.id, isActive: false }, data: { isActive: true } }); if (!result.count) return res.status(404).json({ success: false, message: 'Savings plan not found.' }); const plan = await getOwned(id, req.user.id); return res.json({ success: true, message: 'Savings plan restored successfully', data: plan ? serialize(plan) : null }); }

async function addEntry(req: Request, res: Response, type: 'DEPOSIT' | 'WITHDRAWAL') { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = (type === 'DEPOSIT' ? depositSavingsSchema : withdrawSavingsSchema).safeParse(req.body); if (!parsed.success) return validationError(res, parsed.error); const data: SavingsEntryInput = parsed.data; try { const result = await getPrismaClient().$transaction(async (tx) => { const plan = await tx.savings.findFirst({ where: { id: typeof req.params.id === 'string' ? req.params.id : req.params.id[0], userId: req.user!.id, isActive: true } }); if (!plan) throw new Error('SAVINGS_NOT_FOUND'); const amount = new Prisma.Decimal(data.amount); if (type === 'WITHDRAWAL' && plan.currentAmount.lessThan(amount)) throw new Error('INSUFFICIENT_SAVINGS'); const nextAmount = type === 'DEPOSIT' ? plan.currentAmount.plus(amount) : plan.currentAmount.minus(amount); const entry = await tx.savingsEntry.create({ data: { savingsId: plan.id, userId: req.user!.id, type, amount, description: data.description || null, date: dateAtStart(data.date) } }); const updated = await tx.savings.update({ where: { id: plan.id }, data: { currentAmount: nextAmount }, select: savingsSelect }); return { updated, entry }; }); return res.status(201).json({ success: true, message: type === 'DEPOSIT' ? 'Savings deposit added successfully' : 'Savings withdrawal completed successfully', data: { ...serialize(result.updated), entry: { ...result.entry, amount: result.entry.amount.toString() } } }); } catch (error) { if (error instanceof Error && error.message === 'SAVINGS_NOT_FOUND') return res.status(404).json({ success: false, message: 'Savings plan not found or inactive.' }); if (error instanceof Error && error.message === 'INSUFFICIENT_SAVINGS') return res.status(409).json({ success: false, message: 'Insufficient savings balance.' }); throw error; } }
export async function depositSavings(req: Request, res: Response) { return addEntry(req, res, 'DEPOSIT'); }
export async function withdrawSavings(req: Request, res: Response) { return addEntry(req, res, 'WITHDRAWAL'); }

export async function getSavingsHistory(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const id = typeof req.params.id === 'string' ? req.params.id : req.params.id[0]; if (!(await getOwned(id, req.user.id))) return res.status(404).json({ success: false, message: 'Savings plan not found.' }); const parsed = savingsHistoryQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const [entries, total] = await getPrismaClient().$transaction([getPrismaClient().savingsEntry.findMany({ where: { savingsId: id, userId: req.user.id }, orderBy: { date: 'desc' }, skip: (parsed.data.page - 1) * parsed.data.limit, take: parsed.data.limit, select: { id: true, type: true, amount: true, description: true, date: true, createdAt: true } }), getPrismaClient().savingsEntry.count({ where: { savingsId: id, userId: req.user.id } })]); return res.json({ success: true, message: 'Savings history retrieved successfully', data: entries.map((entry) => ({ ...entry, amount: entry.amount.toString() })), pagination: { page: parsed.data.page, limit: parsed.data.limit, total, totalPages: Math.ceil(total / parsed.data.limit) } }); }

export async function getSavingsSummary(req: Request, res: Response) { if (!req.user) return res.status(401).json({ success: false, message: 'Authentication is required.' }); const parsed = savingsQuerySchema.pick({ currency: true }).safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const plans = await getPrismaClient().savings.findMany({ where: { userId: req.user.id, ...(parsed.data.currency ? { currency: parsed.data.currency } : {}) }, select: { targetAmount: true, currentAmount: true, currency: true, isActive: true, targetDate: true } }); const result: Record<string, { targetAmount: string; savedAmount: string; remainingAmount: string; totalPlans: number; activePlans: number; completedPlans: number; overduePlans: number }> = {}; for (const plan of plans) { const unit = result[plan.currency] ?? { targetAmount: '0', savedAmount: '0', remainingAmount: '0', totalPlans: 0, activePlans: 0, completedPlans: 0, overduePlans: 0 }; const status = statusFor(plan.currentAmount, plan.targetAmount, plan.targetDate); const remaining = plan.targetAmount.minus(plan.currentAmount); unit.targetAmount = new Prisma.Decimal(unit.targetAmount).plus(plan.targetAmount).toString(); unit.savedAmount = new Prisma.Decimal(unit.savedAmount).plus(plan.currentAmount).toString(); unit.remainingAmount = new Prisma.Decimal(unit.remainingAmount).plus(remaining.greaterThan(0) ? remaining : new Prisma.Decimal(0)).toString(); unit.totalPlans += 1; if (plan.isActive) unit.activePlans += 1; if (status === 'COMPLETED') unit.completedPlans += 1; if (status === 'OVERDUE') unit.overduePlans += 1; result[plan.currency] = unit; } return res.json({ success: true, message: 'Savings summary retrieved successfully', data: result }); }

export async function listAdminSavings(req: Request, res: Response) { const parsed = savingsQuerySchema.safeParse(req.query); if (!parsed.success) return validationError(res, parsed.error); const filters = parsed.data; const plans = await getPrismaClient().savings.findMany({ where: { ...(filters.currency ? { currency: filters.currency } : {}), ...(typeof filters.isActive === 'boolean' ? { isActive: filters.isActive } : {}), ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: 'insensitive' as const } }, { description: { contains: filters.search, mode: 'insensitive' as const } }] } : {}) }, select: { ...savingsSelect, user: { select: { id: true, name: true, email: true } } }, orderBy: { createdAt: 'desc' } }); const enriched = plans.map(serialize); const filtered = filters.status ? enriched.filter((plan) => plan.status === filters.status) : enriched; const start = (filters.page - 1) * filters.limit; return res.json({ success: true, message: 'Admin savings retrieved successfully', data: filtered.slice(start, start + filters.limit), pagination: { page: filters.page, limit: filters.limit, total: filtered.length, totalPages: Math.ceil(filtered.length / filters.limit) } }); }

export async function getAdminSavingsSummary(req: Request, res: Response) { const plans = await getPrismaClient().savings.findMany({ select: { targetAmount: true, currentAmount: true, currency: true, isActive: true, targetDate: true } }); const result: Record<string, { targetAmount: string; savedAmount: string; remainingAmount: string; totalPlans: number; activePlans: number; completedPlans: number; overduePlans: number }> = {}; for (const plan of plans) { const unit = result[plan.currency] ?? { targetAmount: '0', savedAmount: '0', remainingAmount: '0', totalPlans: 0, activePlans: 0, completedPlans: 0, overduePlans: 0 }; const status = statusFor(plan.currentAmount, plan.targetAmount, plan.targetDate); const remaining = plan.targetAmount.minus(plan.currentAmount); unit.targetAmount = new Prisma.Decimal(unit.targetAmount).plus(plan.targetAmount).toString(); unit.savedAmount = new Prisma.Decimal(unit.savedAmount).plus(plan.currentAmount).toString(); unit.remainingAmount = new Prisma.Decimal(unit.remainingAmount).plus(remaining.greaterThan(0) ? remaining : new Prisma.Decimal(0)).toString(); unit.totalPlans += 1; if (plan.isActive) unit.activePlans += 1; if (status === 'COMPLETED') unit.completedPlans += 1; if (status === 'OVERDUE') unit.overduePlans += 1; result[plan.currency] = unit; } return res.json({ success: true, message: 'Admin savings summary retrieved successfully', data: result }); }
