import { NotificationType, Prisma } from '@prisma/client';
import { getPrismaClient } from '../config/prisma';

type NotificationEntity = 'BUDGET' | 'SAVINGS' | 'GOAL' | 'RECURRING_TRANSACTION' | 'SYSTEM';
type NotificationInput = { userId: string; type: NotificationType; title: string; message: string; entityType?: NotificationEntity; entityId?: string | null; eventKey?: string | null };
const preferenceField: Record<NotificationType, 'budgetNotifications' | 'savingsNotifications' | 'goalNotifications' | 'recurringNotifications' | 'systemNotifications'> = { BUDGET_ALERT: 'budgetNotifications', BUDGET_WARNING: 'budgetNotifications', BUDGET_EXCEEDED: 'budgetNotifications', SAVINGS_REMINDER: 'savingsNotifications', SAVINGS_PROGRESS: 'savingsNotifications', SAVINGS_COMPLETED: 'savingsNotifications', GOAL_REMINDER: 'goalNotifications', GOAL_PROGRESS: 'goalNotifications', GOAL_DEADLINE: 'goalNotifications', GOAL_COMPLETED: 'goalNotifications', RECURRING_UPCOMING: 'recurringNotifications', RECURRING_GENERATED: 'recurringNotifications', SYSTEM: 'systemNotifications' };

async function sendExpoPush(userId: string, title: string, body: string) { const prisma = getPrismaClient(); const preference = await prisma.notificationPreference.findUnique({ where: { userId }, select: { pushEnabled: true } }); if (!preference?.pushEnabled) return; const devices = await prisma.userDevice.findMany({ where: { userId, isActive: true }, select: { expoPushToken: true } }); if (!devices.length) return; try { const response = await fetch('https://exp.host/--/api/v2/push/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(devices.map((device) => ({ to: device.expoPushToken, title, body, sound: 'default' }))) }); if (!response.ok) await response.text(); } catch { /* Push delivery must not roll back an in-app notification. */ } }

export async function createNotification(input: NotificationInput) { const prisma = getPrismaClient(); const preference = await prisma.notificationPreference.upsert({ where: { userId: input.userId }, create: { userId: input.userId }, update: {}, select: { [preferenceField[input.type]]: true, pushEnabled: true } as Prisma.NotificationPreferenceSelect }); if (!preference[preferenceField[input.type]]) return null; try { const notification = await prisma.notification.create({ data: { userId: input.userId, type: input.type, title: input.title, message: input.message, entityType: input.entityType, entityId: input.entityId || null, eventKey: input.eventKey || null } }); await sendExpoPush(input.userId, input.title, input.message); return notification; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') return null; throw error; } }
export function createBudgetNotification(userId: string, type: 'BUDGET_WARNING' | 'BUDGET_EXCEEDED', title: string, message: string, budgetId: string, eventKey: string) { return createNotification({ userId, type, title, message, entityType: 'BUDGET', entityId: budgetId, eventKey }); }
export function createSavingsNotification(userId: string, type: 'SAVINGS_PROGRESS' | 'SAVINGS_COMPLETED', title: string, message: string, savingsId: string, eventKey: string) { return createNotification({ userId, type, title, message, entityType: 'SAVINGS', entityId: savingsId, eventKey }); }
export function createGoalNotification(userId: string, type: 'GOAL_PROGRESS' | 'GOAL_DEADLINE' | 'GOAL_COMPLETED', title: string, message: string, goalId: string, eventKey: string) { return createNotification({ userId, type, title, message, entityType: 'GOAL', entityId: goalId, eventKey }); }
export function createRecurringNotification(userId: string, type: 'RECURRING_UPCOMING' | 'RECURRING_GENERATED', title: string, message: string, recurringTransactionId: string, eventKey: string) { return createNotification({ userId, type, title, message, entityType: 'RECURRING_TRANSACTION', entityId: recurringTransactionId, eventKey }); }
