import { z } from 'zod';
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const createInvestmentSchema = z.object({ name: z.string().trim().min(1).max(160), type: z.enum(['STOCK', 'CRYPTO', 'REAL_ESTATE', 'BUSINESS', 'GOLD', 'OTHER']), description: z.string().trim().max(2000).optional().nullable(), currency: z.enum(['USD', 'SOS']), quantity: z.coerce.number().nonnegative(), averageBuyPrice: z.coerce.number().nonnegative(), currentPrice: z.coerce.number().positive().optional().nullable() });
export const updateInvestmentSchema = z.object({ name: z.string().trim().min(1).max(160).optional(), description: z.string().trim().max(2000).optional().nullable(), currentPrice: z.coerce.number().positive().optional().nullable(), status: z.enum(['ACTIVE', 'SOLD', 'CLOSED']).optional() }).refine((value) => Object.keys(value).length > 0, 'At least one editable field is required.');
export const investmentQuerySchema = z.object({ type: z.enum(['STOCK', 'CRYPTO', 'REAL_ESTATE', 'BUSINESS', 'GOLD', 'OTHER']).optional(), status: z.enum(['ACTIVE', 'SOLD', 'CLOSED']).optional(), currency: z.enum(['USD', 'SOS']).optional(), search: z.string().trim().max(120).optional(), page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(50).default(20) });
export const investmentTransactionSchema = z.object({ type: z.enum(['BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'OTHER']), quantity: z.coerce.number().nonnegative(), price: z.coerce.number().nonnegative(), amount: z.coerce.number().nonnegative(), currency: z.enum(['USD', 'SOS']), transactionDate: date, note: z.string().trim().max(500).optional().nullable() }).superRefine((value, ctx) => { if (['BUY', 'SELL'].includes(value.type) && value.quantity <= 0) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['quantity'], message: 'Quantity must be positive for BUY or SELL.' }); if (['BUY', 'SELL', 'DIVIDEND'].includes(value.type) && value.amount <= 0) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['amount'], message: 'Amount must be positive for this transaction.' }); });
export const investmentIdSchema = z.object({ id: z.string().uuid() });
export type CreateInvestmentInput = z.infer<typeof createInvestmentSchema>;
export type InvestmentTransactionInput = z.infer<typeof investmentTransactionSchema>;
